### ISSUE TITLE
Explain how to get n-sigma errors/covariance matrix in basic tutorial

### ISSUE THREAD

**Issue by jetteodder** [scikit-hep/iminuit#173]
After running migrad I get out the sigma=1 errors if I initially set errordef=1. However, I'd also like to access the sigma=2 errors without running migrad again (extremely slow!). In pyminuit I could simply run hesse setting up=4, but it seems the parameter up is not defined for iminuit. I cannot find the workaround anywhere in the documentation and would therefore like to ask here for a solution.
Thanks a lot,
Jette

**Comment by cdeil** [comment]
@jetteodder - Could you please post a [minimal working example](https://en.wikipedia.org/wiki/Minimal_Working_Example) of what you want to compute using pyminuit.

I'll then try to reproduce it with iminuit. At the moment it's not clear to me if what you ask is possible and I don't have time to play around myself.

**Comment by jetteodder** [comment]
Hi Christoph,

Thanks for looking into this.
Attached please find a minimum working example of code using pyminuit that I’d like to port to iminut.
The key is that I want to change the value of the parameter called errordef for iminuit (up for pyminuit) and see what that does to the estimated errors (rerunning hesse) without having to minimise the function all over again (as I typically work with very complex functions where rerunning migrad takes longer than just rerunning hesse).

Best,
Jette
--
Jette Oddershede
NEXMAP, DTU Physics
+45 2371 2331

**Comment by cdeil** [comment]
@jetteodder - Github doesn't allow attachments.

Can you put the example e.g. into a [gist](https://gist.github.com/) and link to it from the Github issue?

**Comment by jetteodder** [comment]
Just pasted it below, seems a whole lot easier…
/Jette


import minuit as minuit
import time

def f(x,y,z):
return (x-1)**2+(y-2)**2+(z-3)**2

m = minuit.Minuit(f)
t1=time.clock()
m.migrad()
t2=time.clock()
print "time for migrad: %0.1e" %(t2-t1)
print m.up
print m.values
print m.errors
m.up = 0.25
t1=time.clock()
m.hesse()
t2=time.clock()
print "time for hesse: %0.1e" %(t2-t1)
print m.up
print m.values
print m.errors
t1=time.clock()
m.migrad()
t2=time.clock()
print "time for second migrad: %0.1e" %(t2-t1)

**Comment by HDembinski** [comment]
I am really busy for the next two months, so if you could do it I would be very grateful.
