### ISSUE TITLE
Persist-able objects

### ISSUE THREAD

**Issue by alexpearce** [scikit-hep/iminuit#197]
It would be nice to be able to use [pickle](https://docs.python.org/3.5/library/pickle.html), or similar, to persist objects and the information they contain, such as `iminuit.Minuit` and `iminuit.BinnedLikelihood`.

Today, dumping and loading something like `iminuit.Minuit` discards almost all information on the object, making it effectively useless.

**Comment by alexpearce** [comment]
This looks like a good reference:

https://snorfalorpagus.net/blog/2016/04/16/pickling-cython-classes/

**Comment by alexpearce** [comment]
Sorry for the comment spam 😊 

This simple diff already adds a lot:

```diff
diff --git a/iminuit/_libiminuit.pyx b/iminuit/_libiminuit.pyx
index f1bfcde..aa220da 100644
--- a/iminuit/_libiminuit.pyx
+++ b/iminuit/_libiminuit.pyx
@@ -1410,3 +1410,107 @@ cdef class Minuit:
                 raise RuntimeError(
                     ('Cannot understand keyword %s. May be a typo?\n'
                      'The parameters are %r') % (k, parameters))
+
+    def __getstate__(self):
+        return (
+            self.fcn,
+            self.grad_fcn,
+            self.pos2var,
+            self.var2pos,
+            self.initialvalue,
+            self.initialerror,
+            self.initiallimit,
+            self.initialfix,
+            # cdef PythonFCNBase*pyfcn
+            # cdef MnApplication*minimizer
+            # cdef FunctionMinimum*cfmin
+            # cdef MnUserParameterState*last_upst
+            self.errordef,
+            self.tol,
+            self.strategy,
+            self.print_level,
+            self.throw_nan,
+            self.parameters,
+            self.args,
+            self.values,
+            self.errors,
+            self.covariance,
+            self.fval,
+            self.ncalls,
+            self.edm,
+            self.merrors,
+            self.gcc,
+            self.fitarg,
+            self.narg,
+            self.merrors_struct,
+            self.frontend
+        )
+
+    def __setstate__(self, state):
+        (
+            fcn,
+            grad_fcn,
+            pos2var,
+            var2pos,
+            initialvalue,
+            initialerror,
+            initiallimit,
+            initialfix,
+            # cdef PythonFCNBase*pyfcn
+            # cdef MnApplication*minimizer
+            # cdef FunctionMinimum*cfmin
+            # cdef MnUserParameterState*last_upst
+            errordef,
+            tol,
+            strategy,
+            print_level,
+            throw_nan,
+            parameters,
+            args,
+            values,
+            errors,
+            covariance,
+            fval,
+            ncalls,
+            edm,
+            merrors,
+            gcc,
+            fitarg,
+            narg,
+            merrors_struct,
+            frontend
+        ) = state
+        self.fcn = fcn
+        self.grad_fcn = grad_fcn
+        self.pos2var = pos2var
+        self.var2pos = var2pos
+        self.initialvalue = initialvalue
+        self.initialerror = initialerror
+        self.initiallimit = initiallimit
+        self.initialfix = initialfix
+        # cdef PythonFCNBase*pyfcn
+        # cdef MnApplication*minimizer
+        # cdef FunctionMinimum*cfmin
+        # cdef MnUserParameterState*last_upst
+        self.errordef = errordef
+        self.tol = tol
+        self.strategy = strategy
+        self.print_level = print_level
+        self.throw_nan = throw_nan
+        self.parameters = parameters
+        self.args = args
+        self.values = values
+        self.errors = errors
+        self.covariance = covariance
+        self.fval = fval
+        self.ncalls = ncalls
+        self.edm = edm
+        self.merrors = merrors
+        self.gcc = gcc
+        self.fitarg = fitarg
+        self.narg = narg
+        self.merrors_struct = merrors_struct
+        self.frontend = frontend
+
+        # Should we do this?
+        # self.construct_FCN()
```

Example:

```python
import pickle

import iminuit


def f(x, y, z):
    return (x - 2)**2 + (y - 3)**2 + (z - 4)**2

m = iminuit.Minuit(f)
m.migrad()

m2 = pickle.loads(pickle.dumps(m, protocol=2))
print(m2.fcn(m2.values.values())
# 2.0
```

[These](https://github.com/iminuit/iminuit/blob/d0fd35111acd275985cd870390d6bc90907e7832/iminuit/_libiminuit.pyx#L105-L111) are the only members not pickled:

```python
# C++ object state
# TODO find a nicer fix: cdef PythonFCN*pyfcn  #:FCN
cdef PythonFCNBase*pyfcn  #:FCN
cdef MnApplication*minimizer  #:migrad
cdef FunctionMinimum*cfmin  #:last migrad result
#:last parameter state(from hesse/migrad)
cdef MnUserParameterState*last_upst
```

After a very cursory Google, I don't think there's a simple way of pickling C(++) pointers like this, as they reference possibly-complex objects.

There are already some methods to [build the `pyfcn`](https://github.com/iminuit/iminuit/blob/d0fd35111acd275985cd870390d6bc90907e7832/iminuit/_libiminuit.pyx#L835-L850) object, but in what I assume is a somewhat 'new' state (i.e. before the minimisation), and there's a method to [create a `struct` representation of `cfmin`](https://github.com/iminuit/iminuit/blob/d0fd35111acd275985cd870390d6bc90907e7832/iminuit/Minuit2Struct.pxi#L4-L21), but nothing to go the other way. I'm not sure if we can easily resurrect these objects. (One way is re-running `migrad()`, but that mostly defeats the point of persisting `Minuit`…)

Any further help on this would be much appreciated!

**Comment by cdeil** [comment]
I thought [pickles are for delis](https://www.youtube.com/watch?v=7KnfGDajDQw)?

Would adding JSON or HDF5 or any other explicit serialisation make sense?
(even if it means writing some boilerplate code and might be only a partial information / solution)

**Comment by HDembinski** [comment]
I suppose people like pickles because it is so easy to use, and it is a builtin serialization format. I personally use it all the time. Not to store the state of the minimizer though, because I just care about the result, the parameters and their covariance matrix and not how the minimizer got there.
@alexpearce, what was/is your use case?

@cdeil If we decide that serialization is a good thing to have, I think the question of the back-end is secondary. I would go for pickles (haven't watched the vid, yet), because it is what most people would use. JSON is good for web developers, but since it is storing everything in ASCII, read/write is slow. HDF5 is a nice format, it is binary and it in use in the science community, but storing the Minuit state in HDF5 seems like overkill. Also, it adds an external dependency for a feature that I don't think many people will use.

**Comment by alexpearce** [comment]
I was primarily interested in persisting models, but persisting the likelihood and minimization results is also nice so that I can just open it up later and resume working with it, with the iminuit interface, rather than having to perform the fit again.

Sharing with others is another use case. The problem with pickle for that is that a pickle file can execute arbitrary code when unpickled, so one has to trust the source of the file. This isn't a problem when I've created it, or one of my colleagues, but I wouldn't want to open a pickle file from someone I don't know, e.g. if included in the supplementary material of a paper.

**Comment by cdeil** [comment]
I think there's a good chance that this just isn't possible, or only in a complex and limited way for C++ / Python experts for their application, not in a generic way in the `iminuit` library?

If so, then how about adding a section to the docs (or add an FAQ, like they did for emcee [here](http://dfm.io/emcee/current/user/faq/?highlight=pickle#wrapping-c-code))  stating that it's not possible, and maybe if you think it's useful end with: "if you manage to do it, please contribute a description" or link to this issue?

---

Not on-topic, but related to this issue:

I still think a `result_dict` method that puts fit results (e.g. `values`, `errors`, ...) into a Python dict that can be stored e.g. with `json.dump(m.result_dict())` would be nice to have. (Or add the 5-10 lines that would be the implementation of that method to the docs as an example).

Generally even I don't know what exactly happens on Minuit restart, i.e. on repeated calls to `migrad`, `hesse` and `minos`. So again: some docs that explain about Minuit state and what happens on multiple execution (and possibly in-between attribute changes by the user) would be super-useful.

**Comment by HDembinski** [comment]
Regarding a `result_dict`, `migrad(...)` and `hesse(...)` and `minos(...)` already return dicts with the results. These dicts are pickable, I think.

**Comment by HDembinski** [comment]
@alexpearce I can somewhat see the point for IPython notebooks. I don't use them, so I have little experiene with them. But it certainly would be nice if you could do some minimization in a notebook, which may be time consuming, then save the notebook state, and later restore it and get the last state of the minimizer back to continue working.

**Comment by cdeil** [comment]
> Regarding a result_dict, migrad(...) and hesse(...) and minos(...) already return dicts with the results. 

Is it possible to access these dicts also later from the `Minuit` object?
(sorry if this is clear to everyone, I haven't used iminuit in a long time, ...)

> These dicts are pickable, I think.

Maybe add a test to make sure? IMO ensuring that they are JSON serialisable (by calling `json.dumps`) is even more important, because, well, pickles are for delis. But no need to argue, we could just have a test for each.

**Comment by HDembinski** [comment]
You are right, it is good idea to add a test. I honestly haven't checked this, just guessed from the code.

> Is it possible to access these dicts also later from the Minuit object?

Yes.
`migrad()` returns `self.get_fmin(), self.get_param_states()`
`hesse()` returns `self.get_param_states()`
`minos()` returns `self.merrors_struct`, which can ge obtained with `self.get_merrors()` as well
All these can be accessed later as well.

**Comment by HDembinski** [comment]
Okay, I watched the video from Alex Gaynor now. He is a very good speaker, he was very firm and clear on his point. I was aware of these issues, but I do not agree with his hostility towards pickles, at least not in the context of the science community, where you can trust other people. I would not worry about opening a pickle that is in the supplementary materials of a paper.

**Comment by HDembinski** [comment]
So, to summarize. There are two proposals.
1) Provide an interface to convert the internal state of Minuit into dicts of basic types, which are then picklable or jsonable or whatever-serializable.
2) Make the Minuit object itself pickable, this would allow IPythons storemagic to work http://ipython.org/ipython-doc/rel-0.12/config/extensions/storemagic.html

Unpickling of the Minuit object can be made safe, because we have full control over the function that does the unpickling. Even Alex admits that pickles can be made safe, just that it is hard, because the format is inherently unsafe and one has to make an effort in making it safe. Nevertheless, pickles are useful because they are a builtin functionality of Python, and used in many places, such as in storemagic.

**Comment by HDembinski** [comment]
While it is possible get superficial persistence, we do not have full write access to the underlying C++ object. So after saving and restoring the Minuit object, the state is not truly identical. Due to the technical challenges, I will close this.
