### ISSUE TITLE
PyPy on travis?

### ISSUE THREAD

**Issue by piti118** [scikit-hep/iminuit#21]
@cdeil since you are good with travis. Can we do that? I'm wondering if it compiles with pypy.

**Comment by cdeil** [comment]
@arigo, @gutworth, @cfbolz Is it possible now or in the near future to run this package with PyPy?

iminuit is a Cython wrapper for the MINUIT C++ package.

If yes, could you please share a tip on how to get started?

**Comment by arigo** [comment]
Join the #pypy irc channel on irc.freenode.net and ask around.  Basically you need to extend cpyext to add PyBoolObject etc., which should be relatively easy because we already support PyIntObject and so it's a matter of copying the logic.  We even already did it for PyFloatObject in some non-merged-yet branch, "cpyext-ext".

**Comment by cdeil** [comment]
I'm closing this old issue, I think it's unlikely to get it to work and even if the number of users that need iminuit on pypy is probably small.

That said: if anyone is using pypy and makes an attempt to get iminuit to run there, of course, please open a PR or leave a comment here with your findings!

**Comment by arigo** [comment]
As I said, the missing PyBoolObject type  doesn't look too hard to add.  But it's not going to happen if we don't know about it, so I'd still suggest to open an issue on https://bitbucket.org/pypy/pypy/issues/.

**Comment by arigo** [comment]
Correction, PyComplexObject, PyFloatObject and PyBoolObject are all implemented now.  So the error you have is different.  Please tell us what it is now---on a pypy issue :-)

**Comment by cdeil** [comment]
@arigo - thanks for your comments and support!

I'm just not using pypy, I don't even know how to install stuff with it.
Just trying the naive thing gives this 

```
$ conda install -c conda-forge pypy3.5
$ pypy3 setup.py build_ext -i
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools import setup, Extension
ImportError: No module named 'setuptools'
```

and I don't even know how to install setuptools with this pypi
```
$ pypy3 -m pip
/Users/deil/software/anaconda3/envs/iminuit-270/bin/pypy3: No module named pip
```

I would just waste your time with beginner questions trying to get this to work on PyPI, so I won't follow up.

But like I said: if any iminuit user / dev is using pypy, please try to get it to work and let us know how it goes.

**Comment by cdeil** [comment]
It's working! 🎉 

This is amazing. @arigo - I didn't know that by now pypy works well on Python 3, with Numpy, Cython and even complex C++ libs wrapped like iminuit. Thank you for all your work!

To have a record for us: this is how you install things (works for me on macOS):
```
conda install -c conda-forge pypy3.5
pypy3 -m ensurepip
pypy3 -m pip install pytest cython numpy
# get a coffee, everything is build from source
pypy3 -m pip install ipython jupyter
```

matplotlib install doesn't work yet, but it's not essential for iminuit, just used for a few convenience plotting methods:
```
pypy3 -m pip install matplotlib
```
https://gist.github.com/cdeil/60da9d8a640bb42082c3dcbadd86110d#file-gistfile1-txt-L808

This is how you start ipython and Juptyer with pypy:
```
pypy3 -m IPython
pypy3 -m jupyter notebook
```

There's only one fail in the iminuit test suite:
```
pypy3 -m pytest iminuit
```
gives https://gist.github.com/cdeil/739fdb59741318afca524581050f0397

I'm not familiar with that argument inspection code in iminuit; it could very well be a bug on our side, or us just relying on something CPython specific. But @arigo - if you think that should work on pypy, let me know and I'll file an issue there. See https://github.com/iminuit/iminuit/blob/77814d25e7ff968b99de31d15d325e6cda0f242f/iminuit/tests/test_describe.py#L91-L97

**Comment by cdeil** [comment]
Ha ha, a minute ago the discussion on scipy-dev started whether to support pypy:
https://mail.python.org/pipermail/scipy-dev/2018-August/022999.html

@arigo - Good luck there.

I'll quickly try Astropy now, but then I have to go back to work ...

**Comment by HDembinski** [comment]
Wow, really impressive, thank you @cdeil and @arigo for the follow-up!

**Comment by cdeil** [comment]
For Astropy, it didn't just work like it did for iminuit here. I opened an issue there: https://github.com/astropy/astropy/issues/7768

**Comment by HDembinski** [comment]
fixed on develop
