### ISSUE TITLE
Improve Windows CI

### ISSUE THREAD

**Issue by cdeil** [scikit-hep/iminuit#258]
While working on #245 I improved the travis-ci a bit, to add scipy so that the minimize tests run, and to run the notebook tests: https://github.com/iminuit/iminuit/pull/245/files#diff-354f30a63fb0907d4ad57269548329e3

This is a reminder issue that similar improvements should be made for Windows CI in [.appveyor.yml](https://github.com/iminuit/iminuit/blob/master/.appveyor.yml), so that all tests run on Windows, and ideally also a docs build and notebooks test takes place on Windows.

If anyone is using or even developing iminuit on Windows, please consider taking on this task.

**Comment by HDembinski** [comment]
all testing works on windows
