### ISSUE TITLE
test_function_with_maximum xfail

### ISSUE THREAD

**Issue by cdeil** [scikit-hep/iminuit#271]
We have this xfail test:
https://github.com/iminuit/iminuit/blob/cc69ca82949297864b995c1366a0d53beb1f9f31/iminuit/tests/test_iminuit.py#L730-L739

The comment says that this is a Minuit2 upstream bug (that `is_valid` is true in this case).

@HDembinski - Is this true?
If yes we should report it.
If no we should just delete the test. (Maybe this is just normal and expected MIGRAD behaviour?)

**Comment by HDembinski** [comment]
I added this xfail. Yes, we should report it to ROOT. Please keep this, because it serves as a reminder that there is unexpected behavior.

**Comment by HDembinski** [comment]
Just to explain if it is not obvious: this function in the test has no minimum, only a maximum. Still MINUIT finds a "minimum" and considers it "valid".

**Comment by cdeil** [comment]
Ah, I see. I thought MIGRAD just doesn't start.
But it does and terminate at an arbitrary position and claims to have converged:
https://gist.github.com/cdeil/a2f2a6819faebda29f15fbb6535d8d69

Indeed that seems like something that should be improved in MIGRAD.

@HDembinski - Can you file an issue in the ROOT tracker or should I?

**Comment by HDembinski** [comment]
I will file a bug report, but it would be great if you could chime in when it is there, just to show them that this is more than one user.

The reason why I didn't submit this yet, is because I wanted to write a ROOT example code that demonstrates the bug, so that they can reproduce it.

**Comment by HDembinski** [comment]
The bug is now reported upstream: https://sft.its.cern.ch/jira/browse/ROOT-9522

**Comment by HDembinski** [comment]
@henryiii perhaps you are also interested in this MINUIT2 bug.

**Comment by HDembinski** [comment]
Since this problem is upstream, should we keep this issue open? I removed the bug label, because it is not a bug in our code.

**Comment by cdeil** [comment]
Most projects (Numpy, Astropy, ...) keep issues open as long as users are still affected, even if it's upstream. They just sit there with an "UPSTREAM" label and then, sometimes years later, are resolved.

I would suggest to do things here the same way, so that when someone comes back to coding on iminuit in a few years (like you did a few years after Piti wrote it), they have a list of things to check / work on.

**Comment by HDembinski** [comment]
Fixed upstream! :D
