### ISSUE TITLE
Move iminuit and probfit to Scikit-HEP

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#299]
I am happy to announce that iminuit will become part of the Scikit-HEP organisation.
https://github.com/scikit-hep/
There have been talks between the iminuit team and the Scikit-HEP project leaders and we believe that by joining our communities, we come closer to the goal of establishing a standard scientific Python stack for HEP analyses.

iminuit will not grow new dependencies as part of the merger. probfit will also move to to Scikit-HEP and may in time become more integrated with other Scikit-HEP projects.

The move is planned for mid November and will be announced on the mailing list as well.

**Comment by HDembinski** [comment]
Move has happened.

**Comment by cdeil** [comment]
@HDembinski and scikit-hep - 🎉  Thank you for making this happen! 🎉

**Comment by HDembinski** [comment]
:)
