### ISSUE TITLE
Replace source copy of Minuit2 C++ code with git submodule to GooFit/Minuit2

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#301]
GooFit/Minuit2 is a github repo maintained by @henryiii. It is direct copy of the standalone Minuit2 code from ROOT, in a separate github repo. We should replace our source copy - which has to be manually kept in sync with the original ROOT code with this. It can be included as a git submodule, which is like a link from one github repo to another.

This way, we automatically keep the Minuit2 C++ code up-to-date with the official version, no manual syncing needed.

**Comment by cdeil** [comment]
> no manual syncing needed.

I think you still need to manually move the git submodule pointer, no?

When vendoring a copy you run a command you write once to update, either way it's manual and one command. (I think it's a good thing to have this as a manual step at times of our choosing, we don't want Minuit2 to change all the time)

**Comment by HDembinski** [comment]
I agree with you that we don't want to follow Minuit2 automatically, but as far as bug-fixes are concerned, we would like to keep in sync. And yes, there is still a manual step involved, but it is a simple step.

**Comment by HDembinski** [comment]
Implemented in develop branch.
