### ISSUE TITLE
Add FAQ section

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#304]
This should give advice on some FAQs like:
- Do I need to run HESSE or not.
- What happens when I change the strategy.
- What does errordef mean? What to chose for likelihood function and what for chi2 function?
- How do I get Hesse errors for sigma=2, 3, ...
- How to interpret Hesse errors?

Please add more questions.

**Comment by HDembinski** [comment]
@cdeil Do you have more questions for the FAQ section?

**Comment by HDembinski** [comment]
- Explain why some messages appear on the console when you activate print_level 2.

**Comment by cdeil** [comment]
- give line of code how to get a parameter error (or all errors) from the covariance matrix
- Is there an "ftol" or "xtol" parameter to adjust when MIGRAD stops?
- Will setting parameter limits / the transform that MINUIT does affect parameter errors?
- I'm not sure if optimisation or error estimation is reliable -> plot likelihood profile, check that parameter estimat is at the bottom and it's roughly parabolic
- What should I do if I have a non-physical parameter region that isn't simple limits? (e.g. x > y) -> try to return 1e20 in that case as likelihood, but know that that's a hack. Consider re-parametrising your model.

Maybe put a page with a few and very short answers, and then ask for further feedback / useful additions for this on the iminuit mailing list?

**Comment by cdeil** [comment]
Also: - My signal significance is only 2 sigma, I need at least 3. Is there something Minuit can do for me? -> Adjust errordef to get more sigmas!

**Comment by HDembinski** [comment]
Thanks, these are great!

**Comment by HDembinski** [comment]
I want to get get the 1.3.3 release out fast, so I will just start the FAQ page with what we have. We can always extend it. The 1.3.3 release needs to get out soon, because it has this important fix for the exception report, when the user function raises an error.

**Comment by HDembinski** [comment]
Finally added answers to all of this to the FAQs.
