### ISSUE TITLE
iMinuit 1.3 bug 

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/iminuit#317]
ProbFit cannot show the parts of an AddPdf in iMinuit 1.3.x. It fails to parse the function definitions.

```python
from probfit import AddPdf
def f(x): return 1
def g(x, y): return 3
a = AddPdf(f,g)
a.parts() # crash
````

**Comment by HDembinski** [comment]
This has been repaired, right?

**Comment by eduardo-rodrigues** [comment]
Yep, good with the latest probfit release. For "fun" I've just tested it with Python 3 on SWAN at CERN. I reckon you can close.

**Comment by HDembinski** [comment]
Excellent. Nevertheless, I feel uneasy because I did not understand why the parsing was broken. We want iminuit to be backward compatible, this suggests we made a mistake.

**Comment by eduardo-rodrigues** [comment]
I understand that. @henryiii did some studies, using old Cython versions for example. The thing got broken at some point and it went unnoticed for too long. I guess regular releases/work on both iminuit and probfit will prevent such breakings again :-).

**Comment by henryiii** [comment]
I do think something is off in iMinuit, it used to be able to work with old probfit's output. At some point might be worth further investigation.

**Comment by cdeil** [comment]
We should add CI that has builds / tests that covers related packages.

It also helps if CI setup is similar and there's shared knowledge / expertise in the scikit-hep projects.

My suggestion would be to switch iminuit, probfit, and all others that are willing to https://github.com/marketplace/azure-pipelines and make a shared scikit-hep account that at least two people are willing to maintain. (and each project can still do most configs via a YAML file in their repo).

I guess there might be other CI solutions available at CERN that you might be considering?
Did you have discussions on that already?

Bring that point up on the mailing list? Or just go ahead and try it out?
I'd be interested to help set that up.

**Comment by eduardo-rodrigues** [comment]
Hi @cdeil, nobody in Scikit-HEP has tried that as far as I know. Certainly not for the packages hosted in the org. But if you have positivite experience and have reasons for this, then that's certainly an excellent topic to bring up in the admins list. Thanks 👍 .

**Comment by cdeil** [comment]
I sent an email. By the way: it would be useful if you add some more info at http://scikit-hep.org/help.html , namely (I presume) that the admin list is private, but anyone can send an email there without signing up? And a link to https://groups.google.com/forum/#!forum/scikit-hep-forum would be useful to get to the archives and to sign up if one isn't there already.

**Comment by eduardo-rodrigues** [comment]
You are 100% right. The scikit-hep.org pages need a massive refresh. They are totally out-of-date and inadequate given the present status of the project. It's high on my to-do list to try and get something new there. I should then ask for feedback … Thanks for the ping!
