### ISSUE TITLE
[BUG] `minos()` ignores `var` argument

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/iminuit#318]
Calling e.g. `.minos(var='a')` (assuming I used migrad with variables 'a', 'b') will return the same as no argument given: the dict `{'a': results_a, 'b': results_b}`.

Example
```python
from iminuit import Minuit

minimizer = Minuit(lambda a, b: a**2+2*b**2, forced_parameters=('a', 'b'), a=1, b=2)
fmin, param = minimizer.migrad()
assert not minimizer.minos() == minimizer.minos(var='a')
```

**Comment by HDembinski** [comment]
Ok, solution found. In your `assert`, you first call `minos()` without arguments. This computes the MINOS errors for both parameters. The Minuit class is a state-machine, so it remembers what it has computed before. You when you call `minos(var='a')` the second time in the asserted statement, the MINOS errors for `a` are updated, but the old values for `b` are also still here.

If you would only make a call to `minos(var='a')`, then only the MINOS errors for `a` would be computed and not for `b`, so this is not a bug.

**Comment by mayou36** [comment]
Thanks for the fast reply!

This is a little bit confusing to be honest as usually what get's computed is also what's returned (and what's already computed is cached), but I see how it works and it makes sense to me. I propose to add to the docs though:

`var` is the variable to *compute* the error of. Return a Struct containing *all* up to now computed errors (including `var`).

**Comment by HDembinski** [comment]
Good suggestion, will be included in the docs. And for the record, I agree with your criticism. If I had the opportunity to do iminuit again, I would design it in a much more consistent and logical way. iminuit is the third generation of similar packages and tries to be backward compatible in the interface. That's why it is confusing sometimes.
