### ISSUE TITLE
Constraints on fitting parameters in iminuit?

### ISSUE THREAD

**Issue by alewer97** [scikit-hep/iminuit#331]
Hi, I’ve been trying to fit some parameters to a curve but I need to put a constraint on one of the constants and I don’t know how to make my code acknowledge the constraints and fit a value with the correct value. I’ll try to write a simple example code just to show my problem:

```
def chi(paras):
    mpi=paras[0:32]
    cf=paras[32]
    chif=0
    for i in range(32):
        chif+=((fpi-f(mpi,cf))/error)**2
    return chif
m=Minuit.from_array_func(chi,parin,parstep,name=parname,errordef=1)

fmin,param=m.migrad(ncall=10000)

print(m.values)
```

I want for example cf<=np.log(mpi**2). I’ve tried for example:

```
if cf<=np.log(mpi**2):
    chif+=((fpi-f(mpi,cf))/error)**2
    
else:
    pass
```
but it hasn’t worked. Is there anyway to put this constraint in the code?

**Comment by HDembinski** [comment]
MINUIT supports box constraints, see the `limit` parameter in the docs:
https://iminuit.readthedocs.io/en/latest/api.html#iminuit.Minuit.from_array_func

The limits on a fitted parameter must be **constant** during the minimization. The limits may not depend on other parameters. Sometimes you can substitute parameters to achieve this Let say you have a chi2 with two parameters `a` and `b` and your original constraint was `a + b > 3`. Then you can replace them with two new parameters `x` and `y` with: `x = a + b`, `y = a - b`. Your new function becomes `chi_new(x, y) = chi_old(0.5 * (x + y), 0.5 * (x - y))`. To get the constraint `a + b > 3`, you can now use `x > 3`, which MINUIT supports.

**Comment by HDembinski** [comment]
If am closing this issue, because these questions are better asked on the Scikit-HEP forum: 
https://groups.google.com/forum/#!forum/scikit-hep-forum
The issue tracker is for feature requests and for reporting bugs. Not to ask for help in using iminuit.

**Comment by eduardo-rodrigues** [comment]
BTW, we now have a Gitter channel too, see https://gitter.im/Scikit-HEP/community. You are very welcome to join, @alewer97.
