### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size in Python 3.6 runtime on Travis CI Xenial dist

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/iminuit#332]
Hi @HDembinski, @cdeil, and @piti118. We (the [pyhf](https://github.com/diana-hep/pyhf) team) are noticing that if we try to run our testing suite in the [Travis CI Xenial build environment](https://docs.travis-ci.com/user/reference/xenial/) that [`iminuit` will thrown a `numpy.ufunc` error ](https://travis-ci.org/diana-hep/pyhf/jobs/528365353#L399-L404):

```
    import iminuit
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/iminuit/__init__.py:28: in <module>
    from ._libiminuit import Minuit
__init__.pxd:885: in init iminuit._libiminuit
    ???
E   ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

Poking around it has been hard to find much information on this, beyond https://github.com/gfairchild/pyxDamerauLevenshtein/issues/14, and as I've noticed that [the `iminuit` testing suite doesn't include Python 3.6](https://github.com/scikit-hep/iminuit/blob/3e9167367f5b83901e190dce7fc327cc33d0125b/.travis.yml) I was curious if you had run into something like this before.

The curious thing is that this is a Python 3.6 _only_ issue &mdash; pyhf tests Python 2.7, Python 3.6, and Python 3.7 and Python 2.7 and Python 3.7 pass fine.

**Comment by cdeil** [comment]
That error typically means you compiled a package (iminuit in this case) against a newer version of numpy than the numpy found when you get the error.

The reason you only see this on Python 3.6 is probably that you're doing this (see https://travis-ci.org/diana-hep/pyhf/jobs/528365353#L216):
```
if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip uninstall -y numpy; pip uninstall -y numpy; fi
```

I didn't look at your project or why you're doing that, but probably there's nothing we on the `iminuit` side can do, you have to avoid this issue, probably by avoiding multiple Numpy install / uninstall.

Good luck!

**Comment by cdeil** [comment]
>  I've noticed that the iminuit testing suite doesn't include Python 3.6 I was curious if you had run into something like this before.

I don't think so. We only test 3.5 and 3.7 to have fewer CI builds and save a tree. The assumption is that anything that works on Python 3.5 or 3.7 would also work on 3.6, because Python is very stable within the 3.x series. If there's any doubt about that, a 3.6 CI build should be added for iminuit.

**Comment by matthewfeickert** [comment]
@cdeil Thanks for the comments.

> The reason you only see this on Python 3.6 is probably that you're doing this (see https://travis-ci.org/diana-hep/pyhf/jobs/528365353#L216):
> 
> ```
> if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip uninstall -y numpy; pip uninstall -y numpy; fi
> ```

No, this is a testing branch to move from Trusty to Xenial to [solve another problem ](https://github.com/diana-hep/pyhf/issues/468), and the quoted line was to make sure that there wasn't another issue with the some other library installing multiple versions of numpy without us knowing (as the problem I opened this Issue on came up without them). The reason I asked is that it seems that `iminuit` seems to be the only library that depends on numpy that is raising this issue (I'll do a more through test though).

> That error typically means you compiled a package (iminuit in this case) against a newer version of numpy than the numpy found when you get the error.

iminuit is being installed as a wheel, so can you tell me what version of numpy you build your wheel with (in this case [iminuit v1.3.3](https://pypi.org/project/iminuit/1.3.3/))? Also, I'm confused by this statement because if this is true then why are we not seeing the same error in our Python 2.7 and Python 3.7 tests?

>  The assumption is that anything that works on Python 3.5 or 3.7 would also work on 3.6, because Python is very stable within the 3.x series. If there's any doubt about that, a 3.6 CI build should be added for iminuit.

Hm. There were a [lot of changes/added features in Python 3.6](https://docs.python.org/3/whatsnew/3.6.html), and as it seems that Python 3.6 is the generally accepted lowest version of modern Python that people use given the addition of f-strings I would given the (unasked for) suggestion to test on Python 3.6 if you only want to test on Python 3.7 and then one other. Though you may have different reasons for testing on Python 3.5 then I can think of.

**Comment by cdeil** [comment]
We are not building and distributing binary wheels for iminuit.
Only sdist source distribution here: https://pypi.org/project/iminuit/#files

You / pip are building iminuit when you `pip install .` your package and have iminuit listed as a dependency.

I think you do this for one version of Numpy - the iminuit build works fine.
Then you uninstall the Numpy that was used to build iminuit  for some reason, and try to import iminuit with another (older) version of Numpy.
This is the issue - you have to fix it: build iminuit with the same Numpy version that you then want to use to run it.

I realise this is a bit complex - but I don't have time to look at your builds and issue why you `pip uninstall numpy` or how to structure your build to make it work. Hope this info helps a bit. Good luck!

**Comment by cdeil** [comment]
If you don't believe that the issue has nothing to do with Python 3.6 specifically - feel free to send a PR that adds a Python 3.6 build for our iminuit repo. I would bet that it'll pass. Just for fun, no money. :-)
Might be good to have, one more build really doesn't cost much - I'd merge the PR.

**Comment by matthewfeickert** [comment]
> We are not building and distributing binary wheels for iminuit.
> Only sdist source distribution here: https://pypi.org/project/iminuit/#files

Ah, whoops. I assumed that you were distributing wheels, but yeah you're only doing sdist. This is a separate question for another time, but do you plan to distribute wheels in the future?

> I think you do this for one version of Numpy - the iminuit build works fine.
> Then you uninstall the Numpy that was used to build iminuit for some reason, and try to import iminuit with another (older) version of Numpy.
> This is the issue - you have to fix it: build iminuit with the same Numpy version that you then want to use to run it.

I see what you're saying given the way I presented the original problem, but I don' think that's the issue here, as the whole uninstall/install thing was to do some other checks.

> I realise this is a bit complex - but I don't have time to look at your builds and issue why you `pip uninstall numpy` or how to structure your build to make it work. Hope this info helps a bit. Good luck!

Sure, I also don't expect you to take time to work on my project for me. :) I appreciate you taking time on a Sunday to write back though!

**Comment by matthewfeickert** [comment]
> If you don't believe that the issue has nothing to do with Python 3.6 specifically - feel free to send a PR that adds a Python 3.6 build for our iminuit repo. I would bet that it'll pass. Just for fun, no money. :-)
> Might be good to have, one more build really doesn't cost much - I'd merge the PR.

This is a really great idea for a general test of my issues anyway, so I'll open up a PR. Thanks for the suggestion!

**Comment by cdeil** [comment]
> do you plan to distribute wheels in the future?

I think @HDembinski was considering building & distributing wheels for iminuit.

I'm -1 to do it, unless it's really easy to set up & maintain the build and upload for all platforms (Linux, Mac, Windows) and @HDembinski or someone else wants to maintain it for the coming years.

Other projects do it, it's possible, but it also is some work to set up, and some work to maintain as issues on some user platforms arise.

Note that we do have conda binaries available via conda-forge, see https://iminuit.readthedocs.io/en/latest/install.html

**Comment by matthewfeickert** [comment]
> I think @HDembinski was considering building & distributing wheels for iminuit.
> 
> I'm -1 to do it, unless it's really easy to set up & maintain the build and upload for all platforms (Linux, Mac, Windows) and @HDembinski or someone else wants to maintain it for the coming years.
> 
> Other projects do it, it's possible, but it also is some work to set up, and some work to maintain as issues on some user platforms arise.
> 
> Note that we do have conda binaries available via conda-forge, see https://iminuit.readthedocs.io/en/latest/install.html

Thanks. Just more curious then anything.

If you're considering adding wheels in the future I would be willing to help out. Full disclosure: as the problems with Conda continue to grow I have become increasingly disillusioned with it being the way forward for scientific library distribution, so I'm the type of person who wants everyone to be distributing wheels first. I don't want to be a pest though, but if the project team thinks it could be useful down the line feel free to ping me.

**Comment by cdeil** [comment]
@matthewfeickert - Thanks for the offer of help concerning wheels.

I've already stated my concerns and that I'm -1 to add it. (unless scikit-hep can get some funding and an engineer to set up and maintain wheel builds for their projects - then I'd change to +1)

Given that this issue is mostly a question (and my guess is usage error / expected behaviour when using `pip uninstall numpy` like I mentioned and should be closed soon) - I would suggest to open a short & clean new issue as a feature request "Distribute iminuit wheels via PyPI". And then @HDembinski or others will respond when they see it.

**Comment by matthewfeickert** [comment]
[This Python 3.6 build on Travis CI's Xenial dist for `iminuit` passes](https://travis-ci.org/scikit-hep/iminuit/jobs/528537857), so this isn't `iminuit`'s problem. Closing this issue now.
