### ISSUE TITLE
Distribute iminuit as a wheel on PyPI

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/iminuit#334]
It would be quite nice if `iminuit` would distribute wheels for the library on PyPI. [Wheels](https://wheel.readthedocs.io/en/latest/) make installation much faster and given that not everyone wants to use a very bulky system like Conda (which is [currently suffering terrible speed issues](https://www.anaconda.com/understanding-and-improving-condas-performance/) that [mamba](https://github.com/QuantStack/mamba) may or may not fix) it is a great resource for many users to have binary dists available.

At the moment it appears that there are issues with the way that iminuit's CI is setup that the building of wheels is failing. For example, see the following from a [Python 3.6 job on Travis CI](https://travis-ci.org/scikit-hep/iminuit/jobs/528537856#L736-L784)

```
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DWARNINGMSG=1 -I/tmp/pip-req-build-IViZEC/Minuit/inc -I/usr/include/python2.7 -c /tmp/pip-req-build-IViZEC/iminuit/_libiminuit.cpp -o build/temp.linux-x86_64-2.7/tmp/pip-req-build-IViZEC/iminuit/_libiminuit.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /tmp/pip-req-build-IViZEC/iminuit/PythonFCN.h:9:0,
                   from /tmp/pip-req-build-IViZEC/iminuit/_libiminuit.cpp:723:
  /tmp/pip-req-build-IViZEC/iminuit/PythonCaller.h:10:31: fatal error: numpy/arrayobject.h: No such file or directory
   #include "numpy/arrayobject.h"
                                 ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for iminuit
```

However, if these issues can be fixed then the good news is that having the CI build and distribute wheels is [incredibly simple](https://github.com/diana-hep/pyhf/blob/b6edffae1a1cb7fc7544052506ad790a81960171/.travis.yml#L145).

If this would be considered in the future I would be willing to give time, as available, to help out on this.

**Comment by eduardo-rodrigues** [comment]
Let me cc @henryiii as he has been thinking a fair bit about wheels for Scikit-HEP packages, see for example the work (PR https://github.com/scikit-hep/particle/pull/111) he has done for the [Particle ](https://github.com/scikit-hep/particle/)package.

**Comment by matthewfeickert** [comment]
@eduardo-rodrigues @henryii You might already be well aware of this, but if you publish to PyPI with Travis CI the distribution of wheels is pretty trivial as Travis will automatically do the build of the dists for you. [We do this for `pyhf`](https://pypi.org/project/pyhf/#files) and haven't had any issues so far.

**Comment by henryiii** [comment]
I would not call it incredibly simple, *unless* you have a pure python wheel. Otherwise, you have to build ManyLinux1 or ManyLinux2010, macOS Python.org, and Windows binaries for all Python versions However, I believe it is a solved problem; see my just-released series of posts [here](https://iscinumpy.gitlab.io/post/azure-devops-intro/), especially the third one:  This is my plan for the Scikit-HEP packages; we can adopt this sort of a distribution system. iMinuit is a prime candidate, I would think. @HDembinski ? Also we should make sure it is available on Conda-Forge.

**Comment by matthewfeickert** [comment]
> I would not call it incredibly simple, unless you have a pure python wheel.

Ah right. Sorry, I keep on forgetting (the main feature of `iminuit`) that you have C++ dependencies to deal with.

**Comment by henryiii** [comment]
The third one is the one on wheels: https://iscinumpy.gitlab.io/post/azure-devops-python-wheels/

The other two build up to that one.

**Comment by HDembinski** [comment]
I also would like to have wheels for the obvious reasons mentioned, but my time is limited and help is appreciated. @matthewfeickert if it is easy for you, would you give it a try?

**Comment by matthewfeickert** [comment]
>  @matthewfeickert if it is easy for you, would you give it a try?

In the next week probably I won't have time as I am rushing on a note. But I can give this a look following NumPy's approach and what @henryiii has covered perhaps in 10 days or so.

@henryiii Can you give a full list of all platforms that you want support for?

**Comment by henryiii** [comment]
I've got this working on:

| System | Arch | Python versions |
|---------|-----|------------------|
| ManyLinux1 (custom GCC 8.3) | 64 & 32-bit | 2.7, 3.5, 3.6, 3.7 |
| ManyLinux2010 | 64-bit | 2.7, 3.5, 3.6, 3.7 |
| macOS 10.9+ | 64-bit | 2.7, 3.6, 3.7 |
| Windows | 64 & 32-bit | 2.7, 3.6, 3.7 |

This comes from boost-histogram; if there's a reason to have it, 3.5 on Windows should be eas(ier) to add (than it would have been for boost-histogram).

Only issue is 32-bit Windows + Python 3.6 or 3.7, where one test fails (I *think* the wheels are fine):

```
================================== FAILURES ===================================
________________________________ test_ackleys _________________________________

    def test_ackleys():
        random.seed(0.258)
    
        m = Minuit(ackleys, x=1.5 * random.random(), y=1.5 * random.random(),
                   error_x=1.7, error_y=1.7,
                   pedantic=False, print_level=0)
        m.tol = 1e-4
        m.migrad()
    
>       assert_allclose(m.fval, 0, atol=1e-6)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=1e-06
E       
E       Mismatch: 100%
E       Max absolute difference: 2.57992756
E       Max relative difference: inf
E        x: array(2.579928)
E        y: array(0)

C:\hostedtoolcache\windows\Python\3.6.8\x86\lib\site-packages\iminuit\tests\test_functions.py:39: AssertionError
============================== warnings summary ===============================
tests/test_minimize.py::test_simple
tests/test_minimize.py::test_simple
tests/test_minimize.py::test_simple
  C:\hostedtoolcache\windows\Python\3.6.8\x86\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 112 from C header, got 124 from PyObject
    return f(*args, **kwds)
```

**Comment by henryiii** [comment]
Results here, if they are visible: https://dev.azure.com/scikit-hep/iMinuit/_build/results?buildId=782

I think you have to be a member of Scikit-HEP on Azure to download the wheels. I can push them to test.pypi.org if needed.

**Comment by matthewfeickert** [comment]
> Results here, if they are visible: https://dev.azure.com/scikit-hep/iMinuit/_build/results?buildId=782

This is brilliant @henryiii! :+1: Thanks so much for taking time out of other things to do this.

> I think you have to be a member of Scikit-HEP on Azure to download the wheels. I can push them to test.pypi.org if needed.

I have no opinion here, so I'll leave it to you if you think it is useful to distribute them on TestPyPI as well (I just use TestPyPI to make sure that pyhf's deployment stage of the CI isn't broken and that the PyPI page isn't rendered wrong). When iminuit `v1.3.6` is released will you then start to publish the wheels on PyPI?

**Comment by HDembinski** [comment]
Any ideas on the failing test? I don't see a problem in iminuit, it looks like the linked numpy version is incompatible with the one loaded when the tests are run.

**Comment by henryiii** [comment]
The one that is loaded when the tests are run is the same as the build; I don't clean or use a different environment or an older numpy when building (probably should). Something odd is happening there, though.

**Comment by HDembinski** [comment]
https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility

**Comment by HDembinski** [comment]
The warning may or may not be related to the error...

**Comment by HDembinski** [comment]
Ok, it is definitely not related, I can reproduce the problem. Fitting the ackley function seems to depend on the starting point. The random number generator is seeded (although very weirdly with a float instead of an int) so it should produce the same number everywhere, but maybe they changed the default random number generator from 3.6 onwards. Tests shouldn't depend on random numbers. I will fix this test, and then this PR should be rebased, and then it should be fine.

**Comment by henryiii** [comment]
Agreed, but I don't see a) why there's a mismatch in the numpy version - both *should* be 1.16.3, and comes from the same install; and,  Cython is supposed to avoid/hide this. https://github.com/cython/cython/pull/2627

**Comment by henryiii** [comment]
I was going to mention that the random number is seeded from a floating point as a future improvement, this will call the hash of the floating point - and hashes are not always guaranteed to be consistent across Python versions and/or systems. I didn't check to see if that changed the test result, but it's really a bad idea to not use an integer.

**Comment by henryiii** [comment]
I'll rebase when it's fixed! Will it target master or develop?

**Comment by HDembinski** [comment]
The ackley function has several minima, https://www.sfu.ca/~ssurjano/ackley.html, so the minimum indeed depends highly on the starting point. MIGRAD is a local minimizer and can be trapped in any local minimum.

**Comment by HDembinski** [comment]
> Agreed, but I don't see a) why there's a mismatch in the numpy version - both should be 1.16.3, and comes from the same install; and, Cython is supposed to avoid/hide this. cython/cython#2627

If you read the SO answer, this is because of a different numpy version compiled into scipy.

**Comment by HDembinski** [comment]
One more reason to hate Cython.

**Comment by henryiii** [comment]
I didn’t need one more... and I already have another one more from pyjet...

**Comment by HDembinski** [comment]
@henryiii I pushed what is hopefully a fix to the develop branch.

**Comment by henryiii** [comment]
Looks good, all passing: https://dev.azure.com/scikit-hep/iMinuit/_build/results?buildId=786

I'll squash and make a PR to develop. I'll also start setting up the release pipeline. I really wish they had a yaml release pipeline instead of having to set the four steps up by hand each time. (There is a JSON export/import, but it doesn't work very well and there no way to *start* setting up a pipeline with an import, probably because it's Microsoft).
