### ISSUE TITLE
Consider moving contribute.rst to top level of repo or adding link to readme.rst

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/iminuit#335]
The [`contribute.rst`](https://github.com/scikit-hep/iminuit/blob/e6aaa8f0f9006b76c92a2287f8f0d6716470625d/doc/contribute.rst) for `iminuit` is currently under `doc` (which I understand as it builds the [corresponding page on your docs](https://iminuit.readthedocs.io/en/latest/contribute.html)). However, it was not clear to me that `iminuit` even _had_ one until I had cloned the repo and started poking around in the `doc` dir.

It is common for most projects to have their `CONTRIBUTING.md/.rst` file in the top level of the repo so that it is very clear before anyone ever opens a PR what is expected for contributions. I understand that this might not be appealing to the `iminuit` team to do so, but would it be possible to get a link to [the docs page](https://iminuit.readthedocs.io/en/latest/contribute.html) in the `readme.rst` page if the actual `contribute.rst` isn't a top level directory file?

**Comment by HDembinski** [comment]
Good suggestion, I added a CONTRIBUTE.md with a link to the contribute.rst file.
