### ISSUE TITLE
fix iminuit project on TestPyPI

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#346]
It is currently not possible for me to upload test releases to PyPI, because there is an existing project there that doesn't belong to me: https://test.pypi.org/project/iminuit/

@cdeil Is this your project, perhaps? The release is from 2015. If so, could you please delete the project, so that I can make a new one under my account?

**Comment by cdeil** [comment]
@HDembinski - I've added you as owner for  https://test.pypi.org/project/iminuit/

So you can now do test releases.

Is that OK?

Deleting and recreating the project on test PyPI shouldn't be necessary / useful?
If you want though, you can - as owner you can do anything you like.

**Comment by HDembinski** [comment]
Thank you, this works! Excellent!
