### ISSUE TITLE
1.3.6 ->PyPI

### ISSUE THREAD

**Issue by DavidMStraub** [scikit-hep/iminuit#347]
You mention on the release page that 1.3.5 should not be used, but 1.3.6 is not on PyPI. Can you please fix that? It makes all the unit tests fail here, for instance: https://github.com/flav-io/flavio/commits/master

Thanks!

**Comment by eduardo-rodrigues** [comment]
Dear David, allow me to get in touch with you via this page: we are trying to know which projects and/or packages make use of any of the packages in the Scikit-HEP toolset. At some point soon I will be adding a page "Who uses Scikit-HEP?" to our website http://scikit-hep.org/.
 I'm very happy to see that phenomenologists also see relevance in some of our tools :-). Would you be OK that we add to the list of users your flavio package? (Anything else from us that you use, BTW?) Many thanks!

**Comment by DavidMStraub** [comment]
Dear Eduardo,
sure! In fact I think iminuit is really great and I use it a lot. I don't yet use any other parts of `scikit-hep` but I should look into it. There might even be some chunks of code that could be merged into it (e.g. [ckmutil](https://github.com/DavidMStraub/ckmutil)).

**Comment by eduardo-rodrigues** [comment]
That's great, many thanks!
Yes, your ckmutil could fit into some analysis tools … To keep in mind for a future chat.

**Comment by HDembinski** [comment]
@DavidMStraub Sorry, we are working on getting not only an sdist distribution out, but also binary wheels to make iminuit even easier to install first time for this release. We hope to finish this today. Sorry for the inconvenience, this is new to us and to me in particular. As a temporary fix, I deleted the botched releases from PyPI, so `latest` should point back to 1.3.3.

**Comment by HDembinski** [comment]
Anyway, I am glad to hear from our users.

**Comment by DavidMStraub** [comment]
Indeed with 1.3.3 being the most recent version on PyPI now, everything works again. Thanks!

**Comment by HDembinski** [comment]
@DavidMStraub I updated iminuit on PyPI to 1.3.6 yesterday, this version should work for you. Could you please confirm?

**Comment by DavidMStraub** [comment]
Confirmed!

**Comment by HDembinski** [comment]
Excellent, thank you!
