### ISSUE TITLE
Minuit output in Jupyter Lab

### ISSUE THREAD

**Issue by marinang** [scikit-hep/iminuit#354]
Hi,

I created a new working environment, and now when using `iminuit`, through `zfit`, I see the output of migrad or Hesse as I would see it in the terminal. Do you know what can cause that? I really like the output with all the colours :D.

![Capture d’écran 2019-07-22 à 10 12 08](https://user-images.githubusercontent.com/24250309/61616652-5d65b180-ac69-11e9-9c17-f8e0120d8667.png)

**Comment by HDembinski** [comment]
Hi, is this iminuit-1.3.7? Because I changed the plotting system recently, the idea was to make it more robust.

**Comment by HDembinski** [comment]
The `FitResult` object in the latest iminuit version has `__repr__` and `_repr_html_` methods. Jupyter should detect the `_repr_html_` method and use it to render nice HTML output.

**Comment by marinang** [comment]
@HDembinski Oops sorry I forgot to mention the version. Yes it's `1.3.7`.
