### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by tlatorre-uchicago** [scikit-hep/iminuit#356]
On the documentation page, the mailing list points to https://groups.google.com/forum/#!forum/iminuit, but that page just says that I don't have permission to access this. Is there still an active mailing list?

Thanks!

**Comment by HDembinski** [comment]
Thank you for reporting, the mailing list on readthedocs is wrong, please try https://groups.google.com/forum/#!forum/scikit-hep-forum

**Comment by HDembinski** [comment]
fixed in develop

**Comment by eduardo-rodrigues** [comment]
Allow me to chip in and say that we also have a Gitter channel, see all info at http://scikit-hep.org/getting-in-touch. You choose what you prefer … :-)
