### ISSUE TITLE
MINOS upper limit doesn't make sense with "hard" boundary at 0

### ISSUE THREAD

**Issue by tlatorre-uchicago** [scikit-hep/iminuit#358]
I'm trying to use minuit to minimize a function which has some hard constraints on some of the parameters (in my case they are probabilities which have to be between 0 and 1). Although you can specify boundary limits for the parameters, based on the documentation this is not recommended if the parameters may end up near these limits because of the way MINUIT internally transforms the variables. Therefore, I was hoping to enforce these constraints by adding a "wall" to my negative log likelihood function which rapidly increases when these parameters are out of bounds and rely on MINOS to get the one sided errors.

In testing this I've noticed that sometimes the errors MINOS reports do not correspond to a change in the likelihood of up which is what I think it should be reporting.

Here is a test script:

```
import numpy as np
import matplotlib.pyplot as plt
import iminuit

def nll(x):
    if x[0] <= 0:
        return 1e9*x[0]**2
    return x[0]**2

x0 = [0]

result = iminuit.minimize(nll,x0,options={'disp':True,'maxfev':100000})
minuit = result.minuit
minuit.hesse()
minuit.minos()

for k in minuit.values:
    print("%s = %.18g +/- %.2g lower = %.2g upper = %.2g" % (k, minuit.values[k], minuit.errors[k], minuit.get_merrors()[k].lower, minuit.get_merrors()[k].upper))

print("nll at minimum = %.18g" % nll(result.x))
print("nll at lower = %.18g" % nll(result.x + minuit.get_merrors()[k].lower))
print("nll at upper = %.18g" % nll(result.x + minuit.get_merrors()[k].upper))

x = np.linspace(-10,10,1000)
plt.plot(x,[nll([i]) for i in x])
plt.show()
```

In this case, I've placed the wall at x = 0. Minuit correctly finds the minimum at 0, and MINOS seems to complete successfully however the upper bound is way too small.

**Comment by HDembinski** [comment]
Hi, this is probably an issue in C++ MINUIT that we are wrapping, so not really something we can fix.

Your wall idea is not really a good fix for the problem that is described in the documentation. For parameters with physical bounds you should use MINUIT in the standard way. You just need to be aware that weird things can be happening when your parameter is close to the limit. HESSE will not give a good error estimate then, MINOS may be ok.

In your example, I think MINOS is thrown off by the fact that your nll has a discontinuity in the first and second derivative at the minimum. MIGRAD/HESSE/MINOS does not like that at all, it wants the first and perhaps the second derivative to be continuous.

**Comment by HDembinski** [comment]
Ok, you are right, the first derivative is continuous at x = 0.
