### ISSUE TITLE
allow users to define custom confidence level in "mncontour" and "draw_mncontour"

### ISSUE THREAD

**Issue by Fengpeng-An** [scikit-hep/iminuit#364]
It would be very nice if user can define a custom confidence level in "mncontour" and "draw_mncontour" functions, currently only n*sigma interface is presented. 

In many cases, like in particle physics, people would like to draw 66.7%, 95.5% and 99.7% confidence region  (but not 1,2 and 3 sigmas) in 2D contours. For example, if the parameters are gaussian distributed,  the corresponding change from the minimum of chi^2 FCN can be calculated using:

`from scipy.stats.distributions import chi2`
`chi2.ppf(0.683,df=2)` 
`chi2.ppf(0.955,df=2)` 
`chi2.ppf(0.997,df=2)` 

for other distributions, it is up to the users to figure out the corresponding FCN changes.

Although I can do it by fixing  parameters and sacnning FCN minimum, it would be really handy if users can directly define the values of the change  from the FCN minimum  in "mncontour" and "draw_mncontour" 
Thanks!

**Comment by HDembinski** [comment]
That's a very good suggestion, thank you. Especially since the degrees of freedom that are required for the conversion are known to iminuit, it can do this computation internally.

**Comment by Fengpeng-An** [comment]
Thanks! and thanks for making iminuit, it saves me a lot of time.
