### ISSUE TITLE
contribute iminuit to upstream scipy.optimize?

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/iminuit#365]
at CHEP I discussed with a few people @matthewfeickert @eduardo-rodrigues @mayou36 and others about the possibility of contributing parts of MINUIT to upstream scipy.optimize 

e.g. perhaps MIGRAD could become a `method` as an alternative to e.g. SQLSP, L-BFGS, etc?

@HDembinski is this something you would consider?

**Comment by HDembinski** [comment]
I would like that, but the C++ MINUIT code is tightly integrated, you cannot easily separate out MIGRAD. It would also be a lot of work with little benefit.

**Comment by HDembinski** [comment]
You can do the reserve, though, if you are used to scipy.minimize, we have iminuit.minimize which mimics the interface so you can easily switch between the two.

**Comment by matthewfeickert** [comment]
> You can do the reserve, though, if you are used to `scipy.minimize`, we have `iminuit.minimize` which mimics the interface so you can easily switch between the two.

The idea was more to try to get MINUIT out to the broader world as we were discussing trying to contribute out code to upstream projects.

**Comment by HDembinski** [comment]
@matthewfeickert Hi, I wrote you an email to your CERN account a while ago, did you see it?

I am all for integrating iminuit into scipy, but there are several issues. 

1) I cannot do it with my time budget. If someone wants to try, I am happy to lend support. You have to join the scipy community, get their trust, learn how to integrate MINUIT2 in the scipy build, pass review. I don't know this community. Could be easy, could be difficult. It is certainly not something that's done in a day or two.

2) Is iminuit compatible with scipy? I just had a look into the repo.

Pro:
- They already use Cython.
- They already have some C++ code.

Con:
- They only include BSD-style licensed code. MINUIT2 (the C++ part) is GPLv2. I suppose that would be a show stopper for them.

**Comment by matthewfeickert** [comment]
> @matthewfeickert Hi, I wrote you an email to your CERN account a while ago, did you see it?

Ah very sorry! &mdash; CHEP was a week of poor WiFi connection and overwhelming email loads, so I will go look for it now.

> I am all for integrating iminuit into scipy, but there are several issues.

Thank you for sharing your expert opinions here. You bring up very relevant issues. My posting wasn't meant to challenge your initial response, but just to try to add some additional context on why were were thinking of such an idea in the first place.

**Comment by HDembinski** [comment]
No problem, now the arguments are here for posterity.
