### ISSUE TITLE
Add documentation for the ability to modify parameter values and fixing/releasing after initial set-up

### ISSUE THREAD

**Issue by knikolop-bham** [scikit-hep/iminuit#372]
Dear all,

after many years of using Minuit in its Fortran and C++ incarnations, 
i have recently started using iminuit.

the first thing i noticed that is missing with respect to the Fortran/C++ versions of Minuit is the possibility to modify parameter values and fixing/releasing a parameter (in a way that broadcasts the information to all the relevant places) after the initial set-up (for example, in between calls to migrad).

it seems to me that such a possibility would greatly simplify things when trying to minimize complicated functions and/or when trying to profile certain parameters. I apologise in advance in case this is already possible.

**Comment by HDembinski** [comment]
Hi, I implemented this a while ago, see https://github.com/scikit-hep/iminuit/blob/develop/iminuit/tests/test_iminuit.py#L890. It should be advertised in the basic tutorial...

**Comment by HDembinski** [comment]
fixed in develop
