### ISSUE TITLE
Error bars make no sense for a simple fit

### ISSUE THREAD

**Issue by steveehlert** [scikit-hep/iminuit#377]
I am not sure if this is an iminuit fix or an underlying issue with minuit, but I am running into some serious confusion about the errors it is calculating on an allegedly "converged" fit using a simple chi-squared statistic. The chi-square value makes perfect sense, but the parameter errors are absurdly small. Looking at the Hesse matrix values and profile plot, it looks like it is defining its errors in a far more restrictive sense than it should (delta-chisq < 0.1 instead of delta-chisq < 1 for 1-sigma errors). 

I have done some experiments, but I cannot figure out for the life of me how I may need to change tol or other variables to get this simple fit to behave itself. Do you have any suggestions as to where I should start looking to identify why my error bars are too small?

**Comment by HDembinski** [comment]
Please post a minimal executable code example, then I may be able to help. iminuit's error computation has no known bugs and works for many people, so the problem is probably in your code, but I can still try to help. Also, try running `.minos()` and check those errors.

You may have two almost perfectly (anti-)correlated variables in your fit. In this case, the numerical error calculation cannot work.

**Comment by steveehlert** [comment]
I am afraid I cannot provide a fully executable example (the code base is large and not public), but here is the class I am trying to use for the least-squares determination. The idea is you provide a model function and a different Python object (called **fitter**) to determine fit statistic. I have checked that the values of chisq it is producing make sense, but somehow the Minos and Hesse errors are both way off from what I expect ( I have other programs that do the same fits so I can verify the chi-sq statistic values and estimate error bars), and don't appear to be sampling the right regions of the parameter space. 

```
class LeastSquares:
    """ This class works with iminuit and utilizes a chi-squared statistic for fitting
    model spectra to data. """
    def __init__(self, this_model, this_fitter, min_energy = 2.25, max_energy = 7.):
        self.model = this_model  # model predicts y for given x
        self.y = this_fitter.spectrum.rate
        self.fitter = this_fitter
        self.stat_err = this_fitter.spectrum.stat_err
        self.func_code = make_func_code(describe(self.model)[1:]) #Iminuit code to map function arguments to fit parameters
        self.min_energy = min_energy  #Energy range of fit
        self.max_energy = max_energy

        mask_low = self.fitter.energy >= self.min_energy
        mask_up = self.fitter.energy <= self.max_energy
        self.energymask = numpy.logical_and(mask_low,mask_up)
        
        
    def __call__(self, *par):  # par are a variable number of model parameters
        #Model that I cannot share publicly
        ym = self.fitter.forward_fold_spectrum(self.model, *par)
        chi = (self.y[self.energymask] - ym[self.energymask])/(self.stat_err[self.energymask])
        
        #print("****")
        #for yy,yym,ee,cc in zip(self.y[self.energymask],ym[self.energymask],self.stat_err[self.energymask],chi): print(yy,yym,ee,cc)
        #print("****")
        chi2 = numpy.sum(chi**2)
        #print(chi2, numpy.shape(chi))
        return chi2
```


This is how I am calling this class within a **fitter** object

```
self.lsq = LeastSquares(spectral_model, self)

minuitarg = {}
i=0
p0=[5., 1.], 
step_p=[1.,0.1]
limit_p = None
#This describe function identifies all of the arguments in the
#input model and sets the minuit steps and limits for each
#of them. 
for kw in describe(self.lsq):
        minuitarg[kw] = p0[i]
        if step_p  is not None:
            error_par ="error_%s" %(kw)
              minuitarg[error_par] = step_p[i]
            if limit_p is not None:
                limit_par ="limit_%s" %(kw)
                minuitarg[limit_par] = limit_p[i]
            i+=1

self.minuit = Minuit(self.lsq, pedantic=True,errordef=1.,**minuitarg)
```

**Comment by HDembinski** [comment]
I cannot spot any obvious error. I am puzzled by the comments in the try except clause. You don't need to specify EDM, it is used by MINOS and MIGRAD automatically to check when the fit has converged. If you get complaints about EDM being to large when you run MINOS, it is very likely that your least-squares cost function has numerical or logical issues, is not smooth but jittery. Maybe you did not set parameter limits, but some parameter values are forbidden. For example, when you fit a normal distribution, the sigma parameter must be positive. It can be any number of these things.

You could try m.draw_profile and m.draw_contour after running MIGRAD to inspect the cost function around the minimum. This is all the advice I can give at this point. In 99 % of these cases, there is a numerical or logical problem with the cost function.
