### ISSUE TITLE
Specifying "bound" in draw_contour() by an array does not work

### ISSUE THREAD

**Issue by zwwi** [scikit-hep/iminuit#378]
The `bound` argument in `contour()` can be both a 2x2 array or a number. The reference says that the arguments of `draw_contour()` is the same as `contour()`, but array does not work for the `bound` argument of `draw_contour()` .

One more question: would you think of making a Julia version of iminuit? 

Thank you for making this great tool.

**Comment by HDembinski** [comment]
Sorry for not replying sooner, this somehow slipped by.

* I will look into the bound argument, this sounds like an interface bug, thanks for reporting this!
* Sorry, I cannot make Julia bindings, since I do not have  expertise in making Julia bindings.

**Comment by HDembinski** [comment]
Thanks for using iminuit :)

**Comment by zwwi** [comment]
Thank you!
Here are some wrappers for using iminuit in julia. It is pretty fast, may be used as an alternative to Cython for performance:

```julia
using PyCall
minuit = pyimport(:iminuit);

function method_argnames(m::Method)
    argnames = ccall(:jl_uncompress_argnames, Vector{Symbol}, (Any,), m.slot_syms)
    isempty(argnames) && return argnames
    return argnames[1:m.nargs]
end

# get the list of function arguments as an Array{Symbol, 1}
function func_argnames(f::Function) 
    ms = collect(methods(f))
    return method_argnames(last(ms))[2:end]
end

# define Minuit that uses forced_parameters to pass the arguments of julia function to iminuit
function Minuit(fcn; throw_nan=false, pedantic=false, print_level=0, errordef=1, 
                grad=nothing, use_array_call=false, kwds...)::PyObject
    forced_parameters = Tuple(func_argnames(fcn)) # get the argument lists of fcn
    return minuit.Minuit(fcn, throw_nan, pedantic, forced_parameters, print_level, 
        errordef, grad, use_array_call; kwds...)
end

function migrad(f::PyObject; ncall = 1000, resume = true, nsplit = 1, precision = nothing)
    return pycall(f.migrad, PyObject, ncall, resume, nsplit, precision)
end

migrad(f::PyObject) = pycall(f.migrad, PyObject)

hesse(f::PyObject; maxcall = 0) = pycall(f.hesse, PyObject, maxcall)
hesse(f::PyObject) = pycall(f.hesse, PyObject)

function minos(f::PyObject; var = nothing, sigma = 1, maxcall = 0)
    return pycall(f.minos, PyObject, var, sigma, maxcall)
end

minos(f::PyObject) = pycall(f.minos, PyObject)
```
Then it can be used as
```julia
ftest = Minuit((x, y) -> x^2 + (y-1)^2;  x = 1, y =2)
migrad(ftest)
```

**Comment by HDembinski** [comment]
I recommend jax or numba to accelerate cost functions. iminuit also works in PyPy.

**Comment by zwwi** [comment]
Hello, thanks for your recommendation.
Just for curiosity, I compared the performance of `jax` with Julia for "Example A: Fit of a gaussian model to a histogram" in your tutorial.  On my laptop, `times["JIT, grad"]` gives 0.024 s and  `times["JIT, no grad"]` gives 0.049 s.  
With exactly the same data generated from Python, translating the functions in your tutorial into Julia, and using `@btime` in the Julia package `BenchmarkTools` to measure the time, I got 11 ms for running `migrad` 10 times, and only 3 ms if I further use `ForwardDiff.gradient` to compute `grad` for the `score` function. So it seems Julia indeed has a very good performance here.

The code I used:

```julia
using PyCall, BenchmarkTools, SpecialFunctions
using ForwardDiff: gradient
np = pyimport(:numpy)
minuit = pyimport(:iminuit)

Minuit_from_array_func(fcn, start; kwds...)::PyObject =  minuit.Minuit.from_array_func(fcn, start; pedantic = false, kwds...)
migrad(f::PyObject) = pycall(f.migrad, PyObject)

function pdf(x, par)
    mu, sigma = par
    z = (x - mu) / sigma
    return exp(-0.5 * z^2) / ((2π)^0.5 * sigma)
end

function cdf(x, par)
    mu, sigma = par
    z = (x - mu) / sigma
    return 0.5 * (1 + erf(z / sqrt(2)))
end

function score(par)
    amp = par[1]
    rest = par[2:end]
    mu = amp * (cdf.(xe[2:end], Ref(rest)) - cdf.(xe[1:end-1], Ref(rest)) )
    result = 2 * sum(@. mu - w * log(mu + 1e-100))
    return result
end

start_values = [1.5 * sum(w), 1.0, 2.0]
limits = [(0, nothing), nothing, (0, nothing)]

m1 = Minuit_from_array_func(score, start_values1, limit=limits1)
m1.strategy = 0

gradfun(pars) =  gradient(score, pars)
m2 = Minuit_from_array_func(score, start_values1, limit=limits1, grad = gradfun)
m2.strategy = 0
```
Then `@btime for i = 1:10; migrad(m1); end` gives 11.3 ms and `@btime for i = 1:10; migrad(m2); end` gives 3.2 ms.

**Comment by HDembinski** [comment]
I think you picked the worse of the two JIT compilers that I mentioned here for comparison.

**Comment by fkguo** [comment]
Hello, I put the julia wrapper of iminuit into a julia package: [https://github.com/fkguo/IMinuit.jl](url).

**Comment by zwwi** [comment]
Hello, I put the julia wrapper of iminuit into a julia package: [https://github.com/fkguo/IMinuit.jl](url).

**Comment by HDembinski** [comment]
Thanks!
