### ISSUE TITLE
iminuit support for Python-3.8

### ISSUE THREAD

**Issue by JLanghoff** [scikit-hep/iminuit#380]
Thanks for the great work!
Just wondering, when iminuiet for 3.8 will be ready?

Best Jesper

**Comment by HDembinski** [comment]
Thanks for the question, have you tried to install it from source on Python 3.8? Does it not work?

**Comment by HDembinski** [comment]
You can already get a binary package from conda forge for Python-3.8.
https://anaconda.org/conda-forge/iminuit/files

**Comment by HDembinski** [comment]
There is also a binary package on Linux for Python-3.8. Are you on Windows or Mac?

https://pypi.org/project/iminuit/#files

**Comment by HDembinski** [comment]
If on Mac, I strongly suggest to set up a conda environment, which should already work for Python-3.8.

**Comment by JLanghoff** [comment]
I am on windows :-) Thanks much for the swift reply.

**Comment by HDembinski** [comment]
Check out the new version 1.3.10, it has wheels for Py38 on Windows.
https://pypi.org/project/iminuit/#files

**Comment by HDembinski** [comment]
Please reopen if this is not a solution for you. :)
