### ISSUE TITLE
automatically deploy binary wheels on tag

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#387]
I would like to automate the deployment of binary wheels. Whenever a new tag is generated on the master, Azure should build the binaries and upload them to PyPI.

@henryiii Could you please help me with this?

**Comment by henryiii** [comment]
I added a branch tag of `v*`, let's see if that works. I believe that shows up as tag in the pipelines. If that works, we can change the tag to `v*.*.*` just to make sure we don't trigger on an actual branch with a name like "v1".

**Comment by HDembinski** [comment]
implemented

**Comment by henryiii** [comment]
:tada:

Eventually, we should move to cibuildwheel and GHA, and this will be a bit simpler, but great that it is now working! The prerelease to test pypi is a cute trick.

**Comment by HDembinski** [comment]
Thanks, I am all for moving to cibuildwheel and GHA, but for now your Azure code is still working and my time is limited, so I am leaving that for later.
