### ISSUE TITLE
Minuit does not update to best minimum

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/iminuit#395]
I found a strange behavior while implementing the custom PLL in zfit, hard to reproduce, maybe it is rooted in Minuit. Probably you have an idea.

These are the steps:
we have: old minimum = 4568.455, new minimum 4568.419

- minimize a function, finds a minimum, "old minimum"
- scanning (fixing parameters, do a minimization, each time with a new minuit instance), find a new minimum
- minimize again (also new instance) with all params floating and taking the param values of the new minimum as the starting values; the minimizer starts out at the new minimum
- this minimization converges, but to the old minimum again, which is worse than the starting point

Do you have an idea why minuit takes the worse point? Any ideas? Many thanks

**Comment by HDembinski** [comment]
It is probably just how MINUIT works. I noticed that it mostly ignores the step-sizes you provide when you start the minimization. So there is that. But even if would use the step-sizes that you provide, at the starting point it does not have the right correlations in the first approximation to the Hesse matrix.

Even if you start at the perfect point, MINUIT will start a local search from there using it usual algorithm, compute an approximation to the gradient and the hesse matrix, then find the next point by doing a Newton step. If the new point is worse than the old point, it should do a line search along the gradient instead.

So in any case, starting at the perfect minimum will make MINUIT walk out of the minimum. It does not seem to remember always when a previous point was already better. This limited memory is probably inherited from its ancient FORTRAN roots, where dynamic memory allocation was not yet invented.

**Comment by mayou36** [comment]
Thanks a lot, I hoped it was a different reason. Do you have any practical advice on how to solve this, e.g. step away 0.5 sigma or such (from hessian) and start it there? Or where to dig deeper, e.g. is someone still actively working on improving Minuit?

**Comment by HDembinski** [comment]
> Do you have any practical advice on how to solve this, e.g. step away 0.5 sigma or such (from hessian) and start it there?

You can try to reduce the tolerance for convergence by setting `Minuit.tol` to a smaller value, this prevents MINUIT from converging too quickly. Or maybe your likelihood has numerical issues and it is not smooth enough near the minimum for Minuit to compute the second derivatives well. In most cases when something weird happens, it is an issue with the cost function.

> Or where to dig deeper, e.g. is someone still actively working on improving Minuit?

Lorenzo Moneta is maintaining it in ROOT. Henry and I committed minor changes to fix issues we encountered. I am probably the person who currently understands the MINUIT internals best.

**Comment by mayou36** [comment]
Sorry, overlooked the update.
Thanks a lot for your reply, I will give this a try.
