### ISSUE TITLE
Interest in having Binder support?

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/iminuit#396]
@HDembinski I've noticed that your _great_ tutorial notebooks are not [Binderized](https://mybinder.org/). If it would be of interest, I would be happy to submit a PR that adds Binder support for the repo. 

c.f.:
- pyhf [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/scikit-hep/pyhf/master?filepath=docs%2Fexamples%2Fnotebooks%2Fbinderexample%2FStatisticalAnalysis.ipynb)
- uproot [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/scikit-hep/uproot/master?urlpath=lab/tree/binder%2Ftutorial.ipynb)

**Comment by matthewfeickert** [comment]
An example of what I'm thinking about: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/scikit-hep/iminuit/docs/add-Binder-support?filepath=tutorial)

**Comment by HDembinski** [comment]
Thanks for the praise on the notebooks and for the offer to contribute. Yes, please submit a PR!
