### ISSUE TITLE
Add autobuild of Binder on PR merge and postBuild revision

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/iminuit#404]
Following up on discussions in PR #397, CI can be added to automatically hit the Binder build API and start a Binder build when a PR is merged so that the iminuit Binder is always ready for users.

In addition to this, the current [`binder/postBuild`](https://github.com/scikit-hep/iminuit/blob/789d2b41e714ec7e2f6be73031e583ccbb994bd7/binder/postBuild) file

https://github.com/scikit-hep/iminuit/blob/789d2b41e714ec7e2f6be73031e583ccbb994bd7/binder/postBuild#L1-L2

could be updated to install a PyPI release of `iminuit` as the Binder usage is focused on tutorials. Given that [`requirements-dev.txt`](https://github.com/scikit-hep/iminuit/blob/e76d408db6b145d9e6db4bb810b28edfe4285bd0/requirements-dev.txt) already includes `matplotlib` then all other tutorial dependencies should already be installed, correct @HDembinski? So the only change would be using

```
 python -m pip install iminuit
```

correct?

**Comment by HDembinski** [comment]
I plan to change the binder button to master on the next release. I don't think it is necessary to update binder on every change of develop.

**Comment by HDembinski** [comment]
We only update master on release, so that should work.

**Comment by HDembinski** [comment]
Sorry, clicked the wrong button!

**Comment by matthewfeickert** [comment]
> We only update master on release, so that should work.... I don't think it is necessary to update binder on every change of develop.

This actually simplifies things quite a bit, and given that what is `master` would be the same thing as in the PyPI release there is probably no need to change what is already in the `postBuild` file.

As there are [4 clusters of the Binder Federation](https://blog.jupyter.org/a-2019-retrospective-from-the-binder-project-57a449517362) and the user doesn't have control over the location (by default) that their Binder will get sent to I can automate the building of the Binder images on changes to `master` if that is interesting to you, but it might be a bit overkill.

**Comment by HDembinski** [comment]
The binder button now points to the master, which does not change as frequently.
