### ISSUE TITLE
Add warning flag in fmin object to signal a parameter being at limit

### ISSUE THREAD

**Issue by luca-giunti** [scikit-hep/iminuit#449]
**iminuit version**
1.3.7 

**Bug description**
For a fit in which a parameter value got stuck at the borders of its min-max range, a `Valid Min.=True` flag is returned. No warning or error is emitted.

**Expected behavior**
I would expect an additional flag in the results table, say `Valid Lim.=True/False`, that should impact the overall `Valid Min.=True/False` flag. Checking if a value is "too close" to its min/max borders can be a little tricky, because a reasonable tolerance should be introduced for the comparison. However, this should be addressed somehow, otherwise the fit results table might be misleading...

**To Reproduce**
```
from iminuit import Minuit
def f(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2
m = Minuit(f, limit_x=(1, 1.4))
re = m.migrad()  # run optimiser
print(re)
```
output:
```
------------------------------------------------------------------
| FCN = 0.36                    |      Ncalls=50 (50 total)      |
| EDM = 7.77E-18 (Goal: 1E-05)  |            up = 1.0            |
------------------------------------------------------------------
|  Valid Min.   | Valid Param.  | Above EDM | Reached call limit |
------------------------------------------------------------------
|     True      |     True      |   False   |       False        |
------------------------------------------------------------------
| Hesse failed  |   Has cov.    | Accurate  | Pos. def. | Forced |
------------------------------------------------------------------
|     False     |     True      |   True    |   True    | False  |
------------------------------------------------------------------
------------------------------------------------------------------------------------------
|   | Name |   Value   | Hesse Err | Minos Err- | Minos Err+ | Limit-  | Limit+  | Fixed |
------------------------------------------------------------------------------------------
| 0 | x    |    1.4    |    0.4    |            |            |    1    |   1.4   |       |
| 1 | y    |    3.0    |    1.0    |            |            |         |         |       |
| 2 | z    |    4.0    |    1.0    |            |            |         |         |       |
------------------------------------------------------------------------------------------
```

**Comment by HDembinski** [comment]
Thank you for the report.

I understand the issue and it is reasonable to add a warning of some sort. A parameter value at a limit cannot be considered a failure generally, it may be acceptable in some cases and inacceptable in others. 

Maybe we can add a flag to the `fmin` table which is yellow if a parameter is at the limit, indicates a warning, not a failure.

**Comment by HDembinski** [comment]
Comment: the fit results look perfectly fine, except for the "Hesse Err" of the fixed parameter.

**Comment by luca-giunti** [comment]
Thanks @HDembinski. From what I understand, it is a known a known issue of MIGRAD that the minimizer will tend to get stuck at the min/max borders (my reference is the[ MINUIT manual](https://root.cern.ch/download/minuit.pdf), section 5.3.1). Therefore, I would argue that at least a clear warning (if you prefer it over a strict failure) should be raised in that case...

**Comment by HDembinski** [comment]
implemented in develop
