### ISSUE TITLE
minos runs on all parameters and crashes if one is fixed

### ISSUE THREAD

**Issue by londumas** [scikit-hep/iminuit#458]
https://github.com/scikit-hep/iminuit/blob/8901bedc411953e95852f3a5545ce9b27d9ab987/src/iminuit/_libiminuit.pyx#L1026
https://github.com/scikit-hep/iminuit/blob/8901bedc411953e95852f3a5545ce9b27d9ab987/src/iminuit/_libiminuit.pyx#L1028

In the latest release you changed to have minos run on all parameters.
The current logic is that if one parameter is fixed, then minos stops and returns.
Using the simple example from the following ticket: https://github.com/scikit-hep/iminuit/issues/188

```
import numpy
import iminuit

nb_sigma_for_minos = 2.
loc   = 0.
scale = 1.
size  = 100000
step  = 0.1*scale
edge  = 4.*scale

numpy.random.seed(42)
rand = numpy.random.normal(loc=loc,scale=scale,size=size)
rand = rand[ numpy.logical_and(rand>loc-edge,rand<loc+edge)]
y,bin_edges = numpy.histogram(rand,bins=numpy.arange(loc-edge,loc+edge,step))
x = (bin_edges[:-1] + bin_edges[1:])/2.
yer = numpy.sqrt(y)

def chi2(mu,sigma,A):
	
	g = A*numpy.exp(-(x-mu)**2/(2.*sigma**2))/(numpy.sqrt(2.*numpy.pi)*sigma)
	
	return numpy.sum(numpy.power((y-g)/yer,2.))
m = iminuit.Minuit(chi2,mu=loc,sigma=scale,A=size*step,error_mu=1.,error_sigma=1.,
 error_A=1.,errordef=0.01,print_level=0)
m.migrad()

m.minos(var='mu',sigma=nb_sigma_for_minos)
print(m.merrors)
```

Returns all parameters instead of only mu:

```
------------------------------------------------------------------------------------
|          |          mu           |         sigma         |           A           |
------------------------------------------------------------------------------------
|  Error   |  -0.6e-3  |  0.6e-3   |  -0.4e-3  |  0.4e-3   |    -6     |     6     |
|  Valid   |   True    |   True    |   True    |   True    |   True    |   True    |
| At Limit |   False   |   False   |   False   |   False   |   False   |   False   |
| Max FCN  |   False   |   False   |   False   |   False   |   False   |   False   |
| New Min  |   False   |   False   |   False   |   False   |   False   |   False   |
------------------------------------------------------------------------------------
```

and running the following

```
import numpy
import iminuit

nb_sigma_for_minos = 2.
loc   = 0.
scale = 1.
size  = 100000
step  = 0.1*scale
edge  = 4.*scale

numpy.random.seed(42)
rand = numpy.random.normal(loc=loc,scale=scale,size=size)
rand = rand[ numpy.logical_and(rand>loc-edge,rand<loc+edge)]
y,bin_edges = numpy.histogram(rand,bins=numpy.arange(loc-edge,loc+edge,step))
x = (bin_edges[:-1] + bin_edges[1:])/2.
yer = numpy.sqrt(y)

def chi2(mu,sigma,A):
	
	g = A*numpy.exp(-(x-mu)**2/(2.*sigma**2))/(numpy.sqrt(2.*numpy.pi)*sigma)
	
	return numpy.sum(numpy.power((y-g)/yer,2.))
m = iminuit.Minuit(chi2,mu=loc,sigma=scale,A=size*step,error_mu=1.,error_sigma=1.,
error_A=1.,errordef=0.01,print_level=0, fix_mu=True)
m.migrad()

m.minos(var='A',sigma=nb_sigma_for_minos)
print(m.merrors)
```

returns nothing instead of the parameters for `A`:

```
<me>/python/3.6.3/bin/ipython:26: IMinuitWarning: Specified variable name for minos is fixed
------------
|          |
------------
|  Error   |
|  Valid   |
| At Limit |
| Max FCN  |
| New Min  |
------------
```

**Comment by HDembinski** [comment]
Thank you for the bug report, sorry for that, apparently we miss unit tests for this case. Will be fixed ASAP.

**Comment by HDembinski** [comment]
@londumas Why is errordef=0.01 used in your example? The only two values for errordef are 0.5 and 1.

**Comment by HDembinski** [comment]
@londumas I applied a fix, can you check by building the develop branch?

**Comment by londumas** [comment]
> @londumas Why is errordef=0.01 used in your example? The only two values for errordef are 0.5 and 1.

I do not know, I resurrected an old code used in https://github.com/scikit-hep/iminuit/issues/188 for an other issue.

**Comment by londumas** [comment]
> @londumas I applied a fix, can you check by building the develop branch?

This sounds like a lot of work :) I am only used to to `pip install iminuit`. What then should I do ? `python setup install`? something like that?

**Comment by HDembinski** [comment]
It is not a lot of work, but I can make it easier for you with a pre-release.

**Comment by HDembinski** [comment]
Please install the beta with this command `pip install -i https://test.pypi.org/simple/ --upgrade iminuit` and let me know whether this fixes the issue (it should, I added a test for it, but just to make sure).

**Comment by londumas** [comment]
@HDembinski, thank you for the work. It works now, even our unittest there passed https://github.com/igmhub/picca.
Thanks for the work.

**Comment by HDembinski** [comment]
Thank you for the quick response! I will turn this into a real release now, should be available in 20 min.
