### ISSUE TITLE
Signature of wrapped functions not recognized

### ISSUE THREAD

**Issue by gonzaponte** [scikit-hep/iminuit#463]
Decorated functions don't satisfy any of the conditions asked by `describe` to identify the function's signature, which means they cannot be used in `LeastSquares`, etc.
This is the simplest example I could think of:

```
from functools import wraps
from iminuit   import describe

def deco(f):
    @wraps(f)
    def g(*args, **kwargs):
        return f(*args, **kwargs)
    return g

def f(x, y):
    return x + y

g = deco(f)

assert describe(f) == ['x', 'y'] # all good
assert describe(g) == ['x', 'y'] # raises TypeError: Unable to obtain function signature
```

I think this is a pretty common use case and it is worth incorporating into iminuit. If you decide to add this feature, I am willing to contribute.

Running iminuit version 1.4.9

**Comment by HDembinski** [comment]
Yes, I agree. If you can make it work with decorators, please go ahead with a PR. Thank you.

**Comment by HDembinski** [comment]
fixed in develop thanks to @gonzaponte
