### ISSUE TITLE
yml file raises ResolvePackageNotFound

### ISSUE THREAD

**Issue by gonzaponte** [scikit-hep/iminuit#470]
I'm using conda to create the virtual environment for development and it doesn't resolve the package dependencies. I get
```
ResolvePackageNotFound: 
  - jaxlib
  - python==3.6
  - jax
```

I've fixed it by replacing the python line with `python = 3.6` and by adding `jax` and `jaxlib` to the list of packages installed by `pip`. I guess that adding `python==3.6` to the `pip` list would also work, but I haven't tried.

I don't know if this is something fixed in a more recent version of conda (I'm using 4.7.12 on Ubuntu 19.10), but maybe someone else has had the same problem.

**Comment by HDembinski** [comment]
I can confirm this. The environment-dev.yml file has become outdated. You can use this line instead:
`conda create -c conda-forge  --name foo_env --file requirements-dev.txt`

I will remove environment-dev.yml and update doc/contribute.rst accordingly.
