### ISSUE TITLE
 I have a troublesome problem ， when i use migrad in my fit 

### ISSUE THREAD

**Issue by XDongiang** [scikit-hep/iminuit#474]
I use migrad to optimize the minimum likelihood fitting , but it rarely uses derivatives!
```
fcn value -128523.58733965538
call fcn 20, run time 0.008479833602905273
fcn value -128492.97150642298
call fcn 40, run time 0.008355140686035156
fcn value -128519.85276268289
call fcn 60, run time 0.008434295654296875
fcn value -128525.84361642036
......
call fcn 420, run time 0.008675575256347656
fcn value -128571.20454286638
call fcn 440, run time 0.008511781692504883
fcn value -128571.26018078084
call fcn 460, run time 0.008504390716552734
=========
fcn call 479
grad call 7
=========
```
why migrad rarely call grad ?
what method can call more grad?

Hope to receive suggestions！ 
Thank you!

**Comment by HDembinski** [comment]
Hi, you need to switch the strategy to 0, otherwise MIGRAD will "test" your analytical gradient at each step against a numerically computed gradient. I think this is bad and I reported it upstream to ROOT.

**Comment by XDongiang** [comment]
> Hi, you need to switch the strategy to 0, otherwise MIGRAD will "test" your analytical gradient at each step against a numerically computed gradient. I think this is bad and I reported it upstream to ROOT.

I add `m.strategy = 0` in my program , but the fitting speed is very slow

**Comment by HDembinski** [comment]
Did the change reduce the number of fcn calls or not? iminuit itself runs always very fast. The run-time of iminuit depends on the run-time of your cost function and/or its gradient. Make those faster.
