### ISSUE TITLE
Compatibility of parameter tables and similar with dark themes

### ISSUE THREAD

**Issue by l-althueser** [scikit-hep/iminuit#477]
Hi iminuit team,

I noticed that some (or all) of the table and matrix representations using latex or html have fixed background colors for a clean and convenient coloring. However, when using dark themes in jupyter lab or vscode the fixed colors are a disadvantage. As a result, white text appears on a white colored table row.

I can image two possible fixes:

1. Removing the background colors or adding a kind of switch for dark or light themes.
2. Setting the font color explicitly in the html and latex outputs and preventing unreadable combinations (One probably also has to set a background color for currently transparent table cells).

As reference, I am talking about the colors set here: https://github.com/scikit-hep/iminuit/blob/develop/src/iminuit/repr_html.py#L7

Example for the current version:
![image](https://user-images.githubusercontent.com/13698969/92901011-72c70d80-f420-11ea-836d-7d6ad7bd8c28.png)

.. if one monkey patches the colors:
![image](https://user-images.githubusercontent.com/13698969/92901101-84101a00-f420-11ea-9b22-beadb1b6e8e2.png)

```
import iminuit
iminuit.repr_html.backgrounds = ("background-color:#252526;", "background-color:#1E1E1E;")
iminuit.repr_html.good_style = "background-color:#415944;"
iminuit.repr_html.bad_style = "background-color:#B17E6A;"
iminuit.repr_html.warn_style = "background-color:#D2D2A4;"
```

Thank you!

**Comment by HDembinski** [comment]
If there is an automatic way to pick up the surrounding style, I would like to implement it, but adding color themes is beyond the scope of iminuit. However, I have no problem adding a section in the docs that demonstrates this monkey-patching. Are interested in adding that to the docs?
