### ISSUE TITLE
bug: missing python_requires

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/iminuit#494]
`python_requires` is missing in `setup.cfg` or `setup.py`. This, for example, produces a bad error message in the case of https://github.com/scikit-hep/scikit-hep/pull/112 where iminuit 1.4 is being pinned on Python 2, and also would mean that `python2 -m pip install iminuit` is now broken when it could install a working 1.3.x release. There's no simple way to fix the problem after several releases are out that I know of (short of rereleasing every Python 3-only version with a `.post1` and a `python_requires` set, and maybe deleting the non-post releases and breaking all locked environments), but for the future, `python_requires=[">=3.6"]` should immediately be added so future Python 3 versions can be dropped gracefully. (or 3.5, whatever your current minimum is).

llvmlite (Numba) learned this the hard way with the dropping of 3.5. They got 2.7 right, but didn't do it for 3.5, and as such, `pip install numba` now fails on Python 3.5. No matter what you set `numba==` to, in fact - it requires both be pinned. It was too hard to go back and patch and post-release both llvmlite and numba to fix this.

**Comment by henryiii** [comment]
PS: you can move the "metadata" parts of setup.py to setup.cfg, it is declarative, cleaner, and can automatically read version attributes/files, readme files, etc without boilerplate code.

**Comment by hugovk** [comment]
> llvmlite (Numba) learned this the hard way with the dropping of 3.5. They got 2.7 right, but didn't do it for 3.5, and as such, `pip install numba` now fails on Python 3.5. No matter what you set `numba==` to, in fact - it requires both be pinned. It was too hard to go back and patch and post-release both llvmlite and numba to fix this.

It may be worth llvmlite "yanking" the bad release: 

> A yanked release is a release that is always ignored by an installer, unless it is the only release that matches a version specifier (using either `==` or `===`). 

https://pypi.org/help/#yanked

**Comment by HDembinski** [comment]
Good point, will be fixed. The impact of this setup bug should be minor, because we still support 3.5.
