### ISSUE TITLE
documentation: custom least-squares function with a number of parameters > 2 and error (Poisson)

### ISSUE THREAD

**Issue by giammi56** [scikit-hep/iminuit#495]
Dear all,

1. It took a bit of time for me to implement errors for a custom least-squares function with a number of parameters > 2, a standard automatic feature of Minuit on ROOT C++, and I would suggest updating the documentation accordingly:

Reading from [the tutorial for generic LS function](https://nbviewer.jupyter.org/github/scikit-hep/iminuit/blob/master/tutorial/generic_least_squares_function.ipynb) about setting n>2 parameters, I found no straightforward connection with [the basic tutorial](https://nbviewer.jupyter.org/github/scikit-hep/iminuit/blob/master/tutorial/basic_tutorial.ipynb) for a custom function with standard error.

Here my code, that fuses together the two things. As a very basic user, I think could be a nice ready-made recipe in the tutorial.

```
# everything in iminuit is done through the Minuit object, so we import it
from iminuit import Minuit
# we also need a cost function to fit and import the LeastSquares function
from iminuit.cost import LeastSquares
from iminuit.util import describe, make_func_code
import traceback

class LeastSquares:
    """
    Generic least-squares cost function with error.
    """
    def __init__(self, model, x, y, err):
        self.model = model  # model predicts y for given x
        self.x = np.array(x)
        self.y = np.array(y)
        self.err = np.array(err)
 
    def __call__(self, *par):  # we accept a variable number of model parameters
        ym = self.model(self.x, *par)
        z = (self.y - ym)/(self.err**2)
        return np.sum(z**2)

class BetterLeastSquares(LeastSquares):
    def __init__(self, model, x, y, err):
        super().__init__(model, x, y, err)
        self.func_code = make_func_code(describe(model)[1:])

def PECD6(x, b1, b2, b3, b4, b5, b6):
    return ((b1*x + 0.5*b3*(5*x**3-3*x) +0.125*b5*(63*x**5-70*x**3+15*x)) / (1 + 0.5*b2*(3*x**2-1) + 0.125*b4*(35*x**4-30**2+3) + 0.0625*b6*(231*x**6-315*x**4+105*x**2-5)))

x_data = ctheta_cred
y_data = cPECD[0]
y_err = errPECD[0]

lsq = BetterLeastSquares(PECD6, x_data, y_data, y_err)

m = Minuit(lsq, limit_b1=(-1, 1))
m.migrad()
```

Please let me know if the code could be improved.

2. At [the basic tutorial page](https://nbviewer.jupyter.org/github/scikit-hep/iminuit/blob/master/tutorial/basic_tutorial.ipynb) I found confusing the definition of the `custom_least_squares(a, b)` at the very top of the tutorial and its use way down at the cell number 20. Maybe this part
```
# a simple least-squares cost function looks like this...
def custom_least_squares(a, b):
    ym = line(data_x, a, b)
    z = (data_y - ym) / data_yerr ** 2
    return np.sum(z ** 2)
```
could be simply moved down to simplify the comprehension.

I hope you find these suggestions helpful.
Thank you very much for your **GREAT** job!

**Comment by HDembinski** [comment]
Thank you for using iminuit and the pointers to improve the documentation! I would be happy to accept a PR if you make the changes? I will answer to the two issues below.

1. You don't have to write the GenericLeastSquares function yourself, there is a generic implementation that you can use in the module iminuit.cost, called LeastSquares. It supports arbitrary many parameters and custom errors on the y-values. It also has a few more advanced features like making it easy to mask out certain values. That being said, I am happy to update the code in the tutorial as you suggest, if you submit the changes in a pull request.

2. Thank you for suggesting that, that sounds very good. Also here, could you submit these changes in a pull request?

Thank you!

**Comment by giammi56** [comment]
1. As stated in the [documentation at cell 3](https://nbviewer.jupyter.org/github/scikit-hep/iminuit/blob/master/tutorial/generic_least_squares_function.ipynb), using the `LeastSquares ` alone would cause an error of signature (TypeError: Unable to obtain function signature). The following code (without errors) returns the signature problem:
```

from iminuit import Minuit
from iminuit.cost import LeastSquares
from iminuit.util import describe, make_func_code
import traceback

class LeastSquares:
    """
    Generic least-squares cost function.
    """
    def __init__(self, model, x, y):
        self.model = model  # model predicts y for given x
        self.x = np.array(x)
        self.y = np.array(y)

    def __call__(self, *par):  # we accept a variable number of model parameters
        ym = self.model(self.x, *par)
        chi2 = np.sum((self.y - ym)**2)
        return chi2

def PECD6(x, b1, b2, b3, b4, b5, b6):
    return ((b1*x + 0.5*b3*(5*x**3-3*x) +0.125*b5*(63*x**5-70*x**3+15*x)) / (1 + 0.5*b2*(3*x**2-1) + 0.125*b4*(35*x**4-30**2+3) + 0.0625*b6*(231*x**6-315*x**4+105*x**2-5)))

x_data = ctheta_cred
y_data = cPECD_norm[0]

# class iminuit.cost.LeastSquares(x, y, yerror, model, loss='linear', verbose=0)
lsq = LeastSquares(x_data, y_data, PECD6)

m = Minuit(lsq, errordef=Minuit.LEAST_SQUARES, limit_b1=(-1, 1), limit_b2=(-1, 1), limit_b3=(-1, 1), limit_b4=(-1, 1), limit_b5=(-1, 1), limit_b6=(-1, 1)) # initial values are 0 by default
m.migrad()
```

2. I will PR the updated documents soon.

Thank you, have a nice weekend!

**Comment by HDembinski** [comment]
included in develop
