### ISSUE TITLE
Redesign of `__init__`

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#518]
Once we have #517 we can deprecate the awkward and error-prone keyword-based initialization in `Minuit.__init__`.

Instead of
```
Minuit(fcn, x=1, y=0, error_x=0.2, limit_x=(0, None), fix_y=True)
```
you would do
```
m = Minuit(fcn, x=1, y=0)
m.limits["x"] = (0, None)
m.errors["x"] = 0.2
m.fixed["y"] = True
```
While this is more manual typing, it is more straight forward programming interface when using Minuit as a backend.

The other keywords `errordef`, `print_level`, `throw_nan` all have defaults and can all be set with properties after `__init__` ran, so they can be removed from init as well. We can still warn if `errordef` is not set, the warning will be delayed until `migrad` or `hesse` are called for the first time.

**Comment by henryiii** [comment]
I would also have a way to do this via standard classes, that is,

```python
m = Minuit(fcn, x=Variable(1, limit=(0,None), error=0.2), y=Variable(0, fixed=True))
```

I would also access this variable and then set the properties on it, like so:

```python
m["x"].limit = (0, None)
m["y"].fixed = True
```

This also makes it easier to print a Variable, as well as reduces coupling.

But short of that, overall it is much better that the weird keyword mangling of `error_<>` and such before!

**Comment by HDembinski** [comment]
This kind of interface is good for a higher-level tool, but not for a low-level library like iminuit.

**Comment by HDembinski** [comment]
It also wouldn't work well with #519

**Comment by HDembinski** [comment]
The current interface allows nice things like:
```
m.fixed = False  # releases all parameters, syntactic sugar for m.fixed[:] = False
m.values = (1, 2, 3)  # sets the parameter values to 1, 2, 3 
```

**Comment by henryiii** [comment]
You could technically do this with a special VariableArray, which would allow:

```python
m[:].fixed = False
m[:].values = (1, 2, 3)
```

But the "simpler" (but arguably much less Pythonic) properties of dicts that are not dicts is still better than string manipulation. Though modifying a class is not as nice (less functional-like) as being able to set it up in one step in the constructor.

**Comment by henryiii** [comment]
PS: to be clear, I still prefer the slightly higher-level design, seeing it as both much more Pythonic and flexible, but I'm also okay with the lower-level design and iMinuit is a bit of a lower level library. I don't think that's really an excuse to shortcut the design unless it is significantly harder to implement or has performance issues, which I don't know if it does here, and I'll leave that up to someone working more closely with it. :)

**Comment by henryiii** [comment]
Also, I'd allow either a simple number, or a Variable instance - a simple number `v` is identical to `Variable(v)`, so #519 would still work exactly the same way. It would be a bit uglier if you wanted to set an array of values to non-simple numbers, but the current #519 proposal doesn't have that either.

This should only be seen as a suggestion to think about - if you still like the current proposal better, by all means go for it.

**Comment by HDembinski** [comment]
It is true that `m.value` etc behaves like a mix of dict and list, but the dict interface is historic baggage. It is rather a list-like with the extra property that `m.value[0]` and `m.value["x"]` are equally understood. It is fairly pythonic. There is no need to wrap everything in a class.

**Comment by HDembinski** [comment]
One reason I haven't mentioned yet for me to reject the common (wrong) design of using a Parameter class as a useful abstraction is the fact, that it does not fit the problem. The fundamental unit in a fit is not the individual Parameter, it is the vector of parameters. One cannot reason about a single Parameter in isolation, because it can be correlated with other parameters. So the smallest unit to reason about is the vector of Parameters.

**Comment by henryiii** [comment]
That is an excellent reason, I agree.

**Comment by HDembinski** [comment]
implemented in develop
