### ISSUE TITLE
Unprotected use of multiprocessing.cpu_count()

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/iminuit#520]
https://github.com/scikit-hep/iminuit/blob/2b47d07b6f4249ff4073d4be2313b07215891df6/cmake.py#L40

This could throw and is currently unprotected. See https://docs.python.org/3.5/library/multiprocessing.html#multiprocessing.cpu_count . Instead, maybe use `os.cpu_count()`, new in 3.4+: https://docs.python.org/3.5/library/os.html#os.cpu_count which returns None instead if undeterminable. 

Suggestion:

```python
njobs = self.parallel or multiprocessing.cpu_count() or 1
```

**Comment by HDembinski** [comment]
Thank you that is a good suggestion, will do.

**Comment by henryiii** [comment]
Looks good! Have I mentioned I love Python 3? :)

**Comment by HDembinski** [comment]
Yes, it is great, and now that we don't have to support 3.5 anymore, I can also use f-strings in libraries...

**Comment by henryiii** [comment]
I am curious to try pyupgrade on iMinuit, see https://github.com/scikit-hep/pyhf/pull/1164.

Good, 3.6+ is great. :)
