### ISSUE TITLE
Segmentation fault when running HESSE without any free parameters

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/iminuit#544]
Hi, I ran into an edge case where a segmentation fault is triggered when trying to run HESSE without any free parameters:

```python
import iminuit

def func(pars):
    return (pars[0]-2)**2

m = iminuit.Minuit.from_array_func(func, [1], errordef=1, fix=[True])
m.migrad()
m.hesse()
```

This segfaults with `iminuit` 1.5.4. I am not sure whether v2 addresses this, but it would be convenient if this could get caught with an error message.

**Comment by HDembinski** [comment]
Right, will be fixed ASAP, thanks for reporting!

**Comment by alexander-held** [comment]
Thank you!

**Comment by HDembinski** [comment]
I will implemented a workaround for this in iminuit, but the core issue is upstream in MnHesse.
