### ISSUE TITLE
Unexpected output when running MINOS

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/iminuit#565]
Hi, I noticed some unexpected stdout output when calling MINOS:

```python
from iminuit import Minuit

def fcn(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2

fcn.errordef = Minuit.LEAST_SQUARES

m = Minuit(fcn, x=0, y=0, z=0)
m.migrad()
m.minos(var="x")
```
prints:
```
return Minos error -9.09851e-10  , 9.10173e-10
```
This is with `iminuit` 1.5.4. I could not get the 2.0 RC to compile immediately, so this might already have been fixed - sorry for the issue if that is the case!

**Comment by HDembinski** [comment]
You can install the latest beta like this `pip install -i https://test.pypi.org/simple/ iminuit==2.0rc1`. I tried the code on develop and I didn't see the error. What was the problem with the compilation?

**Comment by HDembinski** [comment]
Anyway, thanks for reporting!

**Comment by alexander-held** [comment]
Thanks, I forgot to check on test.pypi. Works fine with that now.

I was testing in a container with `python:3.8-slim` that required setting up some more dependencies and did not finish going through that given slow internet. Not sure where that output came from, I had a brief look at the code but could not spot it.

In any case, since the issue is gone on develop and the rc1, I guess this is resolved. Thank you!
