### ISSUE TITLE
Some versions of MSVC not supported

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/iminuit#570]
The following:

https://github.com/scikit-hep/iminuit/blob/f12cd519aa08e244ad71f56fe7a97d42117196e4/cmake_ext.py#L37

is not supported by conda-forge, I get:

```
  CMake Error at CMakeLists.txt:3 (project):
    Generator
      Visual Studio 15 2017 Win64
    does not support platform specification, but platform
      x64
    was specified.
```

The problem is that Conda-forge sets the generator for you, so trying to assume and set things breaks it. If you check for and avoid setting this if `CMAKE_GENERATOR` is set, then I think this will work.

See the `contains_arch` code here: https://github.com/pybind/cmake_example/blob/master/setup.py

**Comment by HDembinski** [comment]
Thanks, I will have a look into this.

**Comment by henryiii** [comment]
Gentle ping - I can't progress on the conda-forge packaging until this supports the conda forge compilers. :)

**Comment by henryiii** [comment]
Sorry, I forgot to close this. Thanks!
