### ISSUE TITLE
Behavior when MINOS finds better minimum than MIGRAD

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/iminuit#571]
Hi, I found the following in the [ROOT 6.22 release notes](https://root.cern/doc/v622/release-notes.html):

> **Minuit2**
> - Fix the case when a new better minimum is found while running MINOS

These two PRs are related: https://github.com/root-project/root/pull/4782, https://github.com/root-project/root/pull/6060.

Is this implemented in `iminuit`? If I understand the description in the PRs correctly, this would mean that if I run something like this

```python
m = Minuit(...)
m.migrad()
minimum_x = m.values["x"]
```

and then for some reason MINOS would find a better minimum

```python
m.minos("x")
```

would that cause MIGRAD to re-run (and would I need to possibly manually run HESSE?), but in any case even if MIGRAD runs would I need to re-read the best-fit values?

```python
minimum_x = m.values["x"]
```

How does `iminuit` currently behave in this scenario?

I imagine this scenario is very rare, but it seems like something that may cause unexpected behavior and I would like to catch it in code that uses `iminuit` if possible.

**Comment by HDembinski** [comment]
iminuit v2 is on ROOT's master right now, so these patches are included. I currently have no test case for this, you are welcome to write one. I don't know whether m.values is correctly updated. What you should do is to check the data objects returned by `Minuit.merrors`, they have flags to tell you when MINOS found a better minimum (that is usually a bad sign).

**Comment by HDembinski** [comment]
@alexander-held Did you do some experiments? I would be interested in integrating a test of the behavior.

**Comment by alexander-held** [comment]
Thank you, great that this code is up to date. I unfortunately do not have a test case at the moment. I am also very interested to find a setup that causes this behavior to catch it in tools that use `iminuit`, and would be happy to contribute such a test to `iminuit` too. It might however take me until next year to find the time to produce such a setup.

**Comment by HDembinski** [comment]
@alexander-held I am not sure why you need so much time to test this. Writing a test takes 5 min, see https://github.com/scikit-hep/iminuit/pull/588/commits/f6aff3443fec5a8e941549e0dd0e50a1a3520e39. I find it a little cheap to open issues for questions you can answer yourself fairly easily.
