### ISSUE TITLE
Tests missing from PyPI source tarball for version 2.0.0

### ISSUE THREAD

**Issue by badshah400** [scikit-hep/iminuit#572]
Tests are missing from the [PyPI source tarball](https://pypi.org/project/iminuit/#files) for version 2.0.0. I don't know if this is by intention, simply pointing out since previous versions did have the tests dir in them.

Having tests in the PyPI tarball helps when packaging iminuit into rpms for openSUSE, as we run the tests while building; for now I am downloading the tests from this GH repo, but that's an extra step I would rather avoid if possible.

Thanks for the great library. btw.

**Comment by henryiii** [comment]
This should have been solved with https://github.com/scikit-hep/iminuit/pull/569

**Comment by HDembinski** [comment]
The source tarball had the tests intentionally excluded, but @henryiii made the case that they should be there and provided the patch.
