### ISSUE TITLE
util.describe fails for certain functools.partial functions

### ISSUE THREAD

**Issue by jnsdrtlf** [scikit-hep/iminuit#608]
I recently came across an issue were I tried to use [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial) to simplify my function. This error only happened when using `*args` or `**kwargs` in the partial function.

### Quick Example

This might not be a very practical example, as the minimum is rather trivial, but one could construct a reasonably difficult function that works the same way. If you are interested in a more real-world example, I'd be happy to share my code which originally lead to this issue.

```python
import numpy as np
from iminuit import Minuit
from functools import partial


def foo(x, *args):
    arguments = np.array(args)
    return np.sum(x - arguments, axis=0)


p_foo = partial(foo, 42)  # x = 42


# Minimum is trivial (should be at args[0] = 0.0 and args[1] = 0.0)
m = Minuit(p_foo, 0.04, 0.02)  # Fails!
```

More specifically, the error is:
```text
AttributeError: 'functools.partial' object has no attribute '__name__'
```
caused by this line:
https://github.com/scikit-hep/iminuit/blob/2b7b4a815629a8ebc97109a2e46887b8139c7715/src/iminuit/util.py#L877

### Cause of this Issue

When the keyword argument `name` is not passed to the `Minuit` constructor, the method [`iminuit.util.describe(callable)`](https://github.com/scikit-hep/iminuit/blob/2b7b4a815629a8ebc97109a2e46887b8139c7715/src/iminuit/util.py#L773) is used to determine the argument names from the functions signature.
In this function, we have the following three functions that help us to retrieve the argument names:

https://github.com/scikit-hep/iminuit/blob/2b7b4a815629a8ebc97109a2e46887b8139c7715/src/iminuit/util.py#L833-L835

The first will fail as a `partial` object has no attribute `func_code`. The second (`_arguments_from_inspect`) usually works fine with `partial` objects as `inspect.signature` returns the correct signature. In this case this would be `("*args",)`. However, `*args` and `**kwargs` are ignored as for these types, we construct our own argument names (`x0`, `x1`, ...). So we will eventually end up in the last function `_arguments_from_docstring` which will fail because there is no attribute `__name__` associated with a partial object. Thus, an exception is raised.

Note that this is not solved by using the `func` attribute that is provided by the partial object. This whole function is not going to work with partial functions as `inspect.getdoc` will always return the following:
```text
partial(func, *args, **keywords) - new function with partial application\nof the given arguments and keywords.
```

### Possible Solution

`_arguments_from_inspect` worked perfectly for the partial function. It got `("*args",)` and returned `()` as it should do. I would suggest adding a `try: ... except: return ()` clause around this part:

https://github.com/scikit-hep/iminuit/blob/2b7b4a815629a8ebc97109a2e46887b8139c7715/src/iminuit/util.py#L877

I would be happy to create a pull request (this would mark my first contribution to this project, how exciting!) but I'm open for ideas!

**Comment by jnsdrtlf** [comment]
I came across this issue when developing a function that fits a polynomial function of arbitrary degree (factors passed as `*args`) using a least squares approach.

One could argue that the use of `functools.parital` should be discouraged in this case. Alternatives as for example a `lambda` expression actually work fine (`__name__` of a lambda expression is `<lambda>` and the docstring is empty). But solving this simple issue could avoid some headache when someone is trying to use `functools.partial` anyway.

**Comment by HDembinski** [comment]
This is a very impressive write-up, it is exceptional that someone takes so much time in looking into the code and understanding the cause of some failure. I agree with the diagnostic. Let's discuss the fix further in the PR.

**Comment by jnsdrtlf** [comment]
Thanks!
