### ISSUE TITLE
Support jac=True ?

### ISSUE THREAD

**Issue by nbiederbeck** [scikit-hep/iminuit#616]
While using `iminuit.minimize` as a replacement for scipy, I get the following error:
```python
raise ValueError("jac=True is not supported, only jac=callable")
```
which is perfectly describing the problem (thanks for that).

Is there a way to support `jac=True`? Or `Minuit(func_and_grad, grad=True)`?

**Comment by nbiederbeck** [comment]
From the [scipy docs]:
> If jac is a Boolean and is True, fun is assumed to return and objective and gradient as an (f, g) tuple.

This should have been my question in the first place.  I forgot to include that information, sorry.

[scipy docs]: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html

**Comment by HDembinski** [comment]
We could techincally support `jac=True` in minimize, but it sends the wrong message. The reason for `jac=True` is that you can compute the value and gradient at the same point more efficiently (e.g. with JAX) than doing the calculation separately. But Minuit does not support that, you won't see speed gains in doing this. It actually might be slower. We don't support `jac=True` so you don't think that this is going to help you.

**Comment by nbiederbeck** [comment]
I understand. Thanks!
