### ISSUE TITLE
API inconsistency with covariance

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/iminuit#618]
It seems that the minimizer has an attribute `covariance`, but no `has_covariance` while it's vice-versa for the `FMin`. This seems somehow inconsistent as the object _with_ `has_covariance` actually does not have it.

I would propose to move them together, both to the minimizer? Or what are your thoughts on this? Is there a reason maybe to be as it is now?

**Comment by HDembinski** [comment]
Extended the FMin docstring.
