### ISSUE TITLE
Simplify merge_func_code

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#623]
@mbaak I merged your patch but I am not at all happy with this function. I am considering to revert this at least partially.

Is this interface needed? What is the use case for each option?
```
        - **skip_first** option boolean to skip prefixing the first argument
          of each function. This should normally be true when prefix is not
          None.

        - **factor_list** option list of functions. For function that skip_first
          should not be applied. The choice of prefix applice to factor_list
          will be in the same order as prefix. Default None

        - **skip_prefix** list of variable names that prefix should not be
          applied to.
```
factor_list should be handled by skip_first. skip_first can either be a boolean or a sequence of boolean with the same length as the list of functions to be merged. The boolean for each function then tells you to skip or not. skip_prefix should be removed.

**Comment by HDembinski** [comment]
Only minimal APIs are elegant and this is non a minimal API.

**Comment by mbaak** [comment]
@HDembinski As far as I'm concerned those three options can be removed, and only the basic merging is supported. 
(I ported the full probfit function for backwards compatibility.) Do you want me to remove them, or will you do it? Should be a simple delete.

**Comment by HDembinski** [comment]
I am happy to do it. Ok if these extra functions are not needed, then I am relieved. I think that the merge_func_code is useful, but I don't like the functionality to rename parameters. This should be a separate utility.
