### ISSUE TITLE
BasicView should accept list of keys and return a sequence of the values

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#625]
@watsonjj wants in https://github.com/scikit-hep/iminuit/issues/621 to have easy access to the parameter names and fitted values for a cost function that is part of the a CostSum. We should mimic the numpy array interface for this, which allows one to pass a list of indices to get a numpy array of the values at those key positions.

```py
m = iminuit.Minuit(..., mu=1, sigma=2, beta=3)

m.values[["mu", "beta"]] # returns [1, 3]
m.values[["beta", "sigma"]] # returns [3, 2]
# etc

# using indices should also work
m.values[[0, 2]] # returns [1, 3]
m.values[[2, 1]] # returns [3, 2]

# likewise for m.parameters, m.covariance, m.fixed
```

**Comment by HDembinski** [comment]
@watsonjj This together with some way to get the parameter names per Cost function in a CostSum would work for you, no?

**Comment by watsonjj** [comment]
Indeed.

**Comment by watsonjj** [comment]
In my experimenting for #621 I did implement this for ValueView. However I wasn't sure on how to do the same for the parameter names (I had to stick with a list comprehension). I can open a PR with just my implementation for the ValueView access.

**Comment by watsonjj** [comment]
The reason I included the ability to use `__getitem__` with a tuple in #627 was because `CostSum._maps[i]` returns tuples. Do we intend the user to have to convert that tuple into a list before passing to `ValueView.__getitem__`?

**Comment by watsonjj** [comment]
The ability to get the parameter names in this same way is still missing. Currently have to do `[minuit.parameters[p] for p in cost._maps[i]]`

**Comment by HDembinski** [comment]
> The reason I included the ability to use `__getitem__` with a tuple in #627 was because `CostSum._maps[i]` returns tuples. Do we intend the user to have to convert that tuple into a list before passing to `ValueView.__getitem__`?

Not really, I would like to allow any sequence, but I was worried that this may cause trouble. If you have a 2D numpy array called `arr`, then `arr[(1, 2)]` and `arr[[1, 2]]` do very different things. I am trying to mimic the numpy array API here, that's why I am concerned about allowing tuples.

**Comment by HDembinski** [comment]
For 1D arrays implemented with BasicView allowing tuples is safe, I think, but people will expect that the same syntax works for util.Matrix, which derives from numpy.ndarray and there it will fail if you use tuples.
