### ISSUE TITLE
API to rename parameters

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#626]
It seems there is a need to rename parameters in some functions, especially when combining likelihoods (what @watsonjj calls simultaneous fits).

It is already possible to rename parameters like this:

```py
def normal_pdf(x, mu, sigma):
   # ...

def my_normal_pdf(x, mu_1, sigma_1):
      return normal_pdf(x, mu_1, sigma_1)
```

For common use this is a bit too much to type. It was proposed in #621 to handle this in the Cost function, but that is not the right place for such a functionality, since it is quite general and it should be applied to the model and not the cost.

We want something like this:
```py
# replace all parameter names
f = make_with_signature(normal_pdf, "x", "mu_1", "sigma_1")
g = make_with_signature(normal_pdf, "x", "mu_2", "sigma_2")

# renaming only some parameters
h = make_with_signature(normal_pdf, mu="mu_1") 
```

@watsonjj and @mbaak please comment.

**Comment by watsonjj** [comment]
Before #621, I took a hard look at how probfit implements this:
https://github.com/scikit-hep/probfit/blob/master/probfit/funcutil.pyx
It seemed to me a bit of a bloated solution, so I opted for the simplest approach which was the Cost function method. But I agree it would be nicer as something that can be applied to the model itself.

One danger that should be avoided when implementing this (and a unittest should be created to test for) is that the function should not be altered globally when a rename occurs. This is made more difficult by the fact that a copy/deepcopy only returns the original function, and is perhaps the cause for the more bloated probfit solution.

**Comment by HDembinski** [comment]
One danger that should be avoided when implementing this (and a unittest should be created to test for) is that the function should not be altered globally when a rename occurs. This is made more difficult by the fact that a copy/deepcopy only returns the original function, and is perhaps the cause for the more bloated probfit solution.

> Before #621, I took a hard look at how probfit implements this:
> https://github.com/scikit-hep/probfit/blob/master/probfit/funcutil.pyx
> It seemed to me a bit of a bloated solution, so I opted for the simplest approach which was the Cost function method. But I agree it would be nicer for the solution to be something that can be applied to the model itself.
> 
> One danger that should be avoided when implementing this (and a unittest should be created to test for) is that the function should not be altered globally when a rename occurs. This is made more difficult by the fact that a copy/deepcopy only returns the original function, and is perhaps the cause for the more bloated probfit solution.

Right.

**Comment by HDembinski** [comment]
> It seemed to me a bit of a bloated solution

Agreed, the probfit code is not good guidance.
