### ISSUE TITLE
minos still needs migrad run first

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/iminuit#631]
First of all, many thanks for making minos independent of previous migrad runs as described [in the changelog](https://iminuit.readthedocs.io/en/latest/changelog.html#id8)

It seems however that this does not yet fully work. As an example the very basic script from the README, feeding the fit result into a new Minuit instance.

```
from iminuit import Minuit

def fcn(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2

fcn.errordef = Minuit.LEAST_SQUARES

m = Minuit(fcn, x=0, y=0, z=0)

m.migrad()  # run optimiser
m.values  # x: 2, y: 3, z: 4

m.hesse()   # run covariance estimator

m2 = Minuit(fcn, **m.values)

m2.hesse()  # works
m2.minos()  # fails (also without previous `hesse`
```

Am I maybe missing something? Or do you have an idea what is going wrong?

**Comment by HDembinski** [comment]
I am a bit confused, because we have a unit test for this and a unit-tested tutorial that demonstrates this feature.
```py
def test_minos_without_migrad():
    m = Minuit(lsq(lambda x, y: (x - 1) ** 2 + (y / 2) ** 2), 1.001, 0.001)
    m.minos()
    me = m.merrors["x"]
    assert me.is_valid
    assert me.lower == approx(-1, abs=5e-3)
    assert me.upper == approx(1, abs=5e-3)
    me = m.merrors["y"]
    assert me.is_valid
    assert me.lower == approx(-2, abs=5e-3)
    assert me.upper == approx(2, abs=5e-3)
```

**Comment by HDembinski** [comment]
This line `m2 = Minuit(fcn, **m.values)` indicates that you are not using iminuit v2.

**Comment by mayou36** [comment]
Silly me! Of course, I tried to make a reproducible snippet and ended up using the wrong interpreter, not realising that the error is different. 

The error still persists, however it is not simply reproducible for me, but happens randomly in the unittests using a more complicated function. Spoiler alert, I was not able to reproduce it with a simple example, unfortunately (so far). However, there seems to be a problem/inconsistency in the algorithm (either in the way it works or in the printing) or a user who does not understand minuit :)

A function is minimized with a different minimizer and then Minuits minos is used. This rarely fails however here: https://github.com/scikit-hep/iminuit/blob/b5c3ddcfec404bbd38695a7bcd24b3f6bf367ea5/src/iminuit/minuit.py#L930

Seemingly the newly created minimum is not valid. I've investigated by jumping inside and it seems that hesse failed. The minimum however seem to be the global one. Also, 

Now the weird thing is: Running migrad (at this position, with the invalid fmin) works and returns (practically) the same values as there were before, so we're at the same minimum. The problem that is fitted is the same as in #613. To illustrate this:

Before, then after
```
<ValueView mu=4.4996302344288175 sigma=2.0131166799575455 lambda=-0.031873869206060224>
<ValueView mu=4.499630245840057  sigma=2.0131147187759826 lambda=-0.03186897890497059>
```
also the fval (exactly the same)
before: 55843.21697906856
after : 55843.21697906856

Running MINOS, it works now.

So what I would suspect is that maybe it is e.g. numerically too unstable to create the hessian, so it fails. But stable enough for migrad and now it has a good enough covariance approximation. One thing I've noticed as well is that it only seems to fail when minos already run before once (such as for another parameter or something).

So far I would have estimated the bug to be somewhere in my code tbh. The turning point is: the output of migrad was weird. It showed the MINOS and HESSE error already computed (Strategy 0 or 1 was used), this is because minos is actually run multiple times, with different cl and different parameters.

Which raises for me two questions: why does it fail on the first time if it already was able to compute the errors before? Like how could that possibly happen? And why does it say that there is no cov (and needs to compute and fails, that's the actual problem) while there "is"?

How come that a migrad call solves this?

Is it actually fine to run minos multiple times with different CLs or is that an abuse (did not find anything in the docs)?

So my guess is that minuit, or the FMin or something shares something that it should not. Or simply the printing is wrong (still begs the question why migrad solves it though)

Do you have an idea what is going on? Many thanks for the help in advance

The full IPython console output for the timeline (the raw data):

<details>
<summary>Details</summary>

fm.state.has_covariance
Out[8]: False
fm.has_covariance
Out[9]: True
fm.is_above_max_edm
Out[10]: False
fm.is_valid
Out[11]: False
fm.fval
Out[12]: 55843.21697906856
fm.has_accurate_covar
Out[13]: False
fm.has_valid_parameters
Out[14]: True
fm.hesse_failed
Out[15]: True
hesse(self._fcn, fm, ncall)
fm.hesse_failed
Out[17]: True
self.values
Out[18]: <ValueView mu=4.4996302344288175 sigma=2.0131166799575455 lambda=-0.031873869206060224>
self.migrad()
Out[19]:
┌──────────────────────────────────┬──────────────────────────────────────┐
│ FCN = 5.584e+04                  │              Nfcn = 721              │ COMMENT JONAS: I tried a lot 
│ EDM = 1.74e-07 (Goal: 0.001)     │                                      │ before with minos and also 
├───────────────┬──────────────────┼──────────────────────────────────────┤ minos run already before,
│ Valid Minimum │ Valid Parameters │        No Parameters at limit        │ that's why Nfcn is so high
├───────────────┴──────────────────┼──────────────────────────────────────┤ (supposedly)
│ Below EDM threshold (goal x 10)  │           Below call limit           │
├───────────────┬──────────────────┼───────────┬─────────────┬────────────┤
│  Covariance   │     Hesse ok     │ Accurate  │  Pos. def.  │ Not forced │
└───────────────┴──────────────────┴───────────┴─────────────┴────────────┘
┌───┬────────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name   │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼────────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ mu     │   4.500   │   0.021   │   -0.042   │   0.041    │   -5    │    9    │       │
│ 1 │ sigma  │   2.013   │   0.015   │   -0.031   │   0.031    │  0.01   │   10    │       │
│ 2 │ lambda │  -0.032   │   0.007   │   -0.014   │   0.014    │  -0.5   │ -0.0003 │       │
└───┴────────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘
┌──────────┬───────────────────────┬───────────────────────┬───────────────────────┐
│          │          mu           │         sigma         │        lambda         │
├──────────┼───────────┬───────────┼───────────┬───────────┼───────────┬───────────┤
│  Error   │   -0.04   │   0.04    │  -0.031   │   0.031   │  -0.014   │   0.014   │
│  Valid   │   True    │   True    │   True    │   True    │   True    │   True    │
│ At Limit │   False   │   False   │   False   │   False   │   False   │   False   │
│ Max FCN  │   False   │   False   │   False   │   False   │   False   │   False   │
│ New Min  │   False   │   False   │   False   │   False   │   False   │   False   │
└──────────┴───────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
┌────────┬───────────────────────────────┐
│        │        mu     sigma    lambda │
├────────┼───────────────────────────────┤
│     mu │  0.000428 -6.41e-06 -7.47e-05 │
│  sigma │ -6.41e-06   0.00024  1.01e-05 │
│ lambda │ -7.47e-05  1.01e-05  4.77e-05 │
└────────┴───────────────────────────────┘
self.values
Out[20]: <ValueView mu=4.499630245840057 sigma=2.0131147187759826 lambda=-0.03186897890497059>
fm.has_valid_parameters
Out[21]: True
fm.fval
Out[22]: 55843.21697906856
fm.state.has_covariance
Out[23]: False
hesse(self._fcn, fm, ncall)
fm.state.has_covariance
Out[25]: False
self.minos(*parameters, cl=cl, ncall=ncall)
Out[26]:
┌──────────────────────────────────┬──────────────────────────────────────┐
│ FCN = 5.584e+04                  │              Nfcn = 827              │
│ EDM = 1.74e-07 (Goal: 0.001)     │                                      │
├───────────────┬──────────────────┼──────────────────────────────────────┤
│ Valid Minimum │ Valid Parameters │        No Parameters at limit        │
├───────────────┴──────────────────┼──────────────────────────────────────┤
│ Below EDM threshold (goal x 10)  │           Below call limit           │
├───────────────┬──────────────────┼───────────┬─────────────┬────────────┤
│  Covariance   │     Hesse ok     │ Accurate  │  Pos. def.  │ Not forced │
└───────────────┴──────────────────┴───────────┴─────────────┴────────────┘
┌───┬────────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name   │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼────────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ mu     │   4.500   │   0.021   │   -0.021   │   0.021    │   -5    │    9    │       │
│ 1 │ sigma  │   2.013   │   0.015   │   -0.015   │   0.016    │  0.01   │   10    │       │
│ 2 │ lambda │  -0.032   │   0.007   │   -0.007   │   0.007    │  -0.5   │ -0.0003 │       │
└───┴────────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘
┌──────────┬───────────────────────┬───────────────────────┬───────────────────────┐
│          │          mu           │         sigma         │        lambda         │
├──────────┼───────────┬───────────┼───────────┬───────────┼───────────┬───────────┤
│  Error   │  -0.021   │   0.021   │  -0.015   │   0.016   │  -0.007   │   0.007   │
│  Valid   │   True    │   True    │   True    │   True    │   True    │   True    │
│ At Limit │   False   │   False   │   False   │   False   │   False   │   False   │
│ Max FCN  │   False   │   False   │   False   │   False   │   False   │   False   │
│ New Min  │   False   │   False   │   False   │   False   │   False   │   False   │
└──────────┴───────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
┌────────┬───────────────────────────────┐
│        │        mu     sigma    lambda │
├────────┼───────────────────────────────┤
│     mu │  0.000428 -6.41e-06 -7.47e-05 │
│  sigma │ -6.41e-06   0.00024  1.01e-05 │
│ lambda │ -7.47e-05  1.01e-05  4.77e-05 │

</details>

**Comment by HDembinski** [comment]
> Which raises for me two questions: why does it fail on the first time if it already was able to compute the errors before? Like how could that possibly happen?

Not sure what to say. Minuit is a state machine. It maintains some memory of what has happened before. We do not fully expose that and tracking exactly what kind of state Minuit remembers is also not so easy. The point is, if you don't want it to maintain state, then use `.reset()`. Otherwise you should expected that the order of calls matters. That is not a bug it is a feature.

**Comment by mayou36** [comment]
I agree, but I don't see why it fails then? And says it has no covariance if asked but prints it out?

Furthermore, I've fixed the problem: Simply removing line https://github.com/scikit-hep/iminuit/blob/b5c3ddcfec404bbd38695a7bcd24b3f6bf367ea5/src/iminuit/minuit.py#L930 and it works.

So this line seems to be preventing minos to run somehow in a case where it actually could. I understand why this is there but it seems to generate false positives. What is the damage by removing the check?

**Comment by mayou36** [comment]
I agree, but I don't see why it fails then? And says it has no covariance if asked but prints it out?

Furthermore, I've fixed the problem: Simply removing line https://github.com/scikit-hep/iminuit/blob/b5c3ddcfec404bbd38695a7bcd24b3f6bf367ea5/src/iminuit/minuit.py#L930 and it works.

So this line seems to be preventing minos to run somehow in a case where it actually could. I understand why this is there but it seems to generate false positives. What is the damage by removing the check?

**Comment by HDembinski** [comment]
Would you stop reopening this? Thanks.

**Comment by HDembinski** [comment]
If you want to discuss things that are not specific issues, please use https://gitter.im/Scikit-HEP/iminuit

**Comment by mayou36** [comment]
We may created a misunderstanding: this is a bug report, but I struggled to find a simple reproducible example. I finally managed! As described in the title, multiple runs of minos (without any change in anything) will raise an error here (if migrad never ran):
https://github.com/scikit-hep/iminuit/blob/b5c3ddcfec404bbd38695a7bcd24b3f6bf367ea5/src/iminuit/minuit.py#L930

Can we maybe re-open this issue?

What seems weird: the number until it fails is fully deterministic _and depends on the cl chosen_. I've plotted the number of minos calls vs the cl

![image](https://user-images.githubusercontent.com/17454848/113353834-8f844d80-933e-11eb-8aa8-b2d3ff628e45.png)

Here is a minimal example (taking the basic example from the docs) to reproduce the issue:

```python
from iminuit import Minuit

def fcn(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2

fcn.errordef = Minuit.LEAST_SQUARES

m = Minuit(fcn, x=2, y=1.3, z=1)
m.migrad()

assert m.fmin.is_valid

m2 = Minuit(fcn,
            x=m.values['x'],
            y=m.values['y'],
            z=m.values['z'])
for i in range(7):  # default cl fails at 7, 6 works
    m2.minos()
```

Using a reset instead of the error (or even ignoring the error and passing) solves the problem seemingly (but I may don't understand Minuit enough for this).

The full script to reproduce the plot

<details>
<summary>Details</summary>

from iminuit import Minuit
import numpy as np

cl = 0.688 # Fails after three for >= 0.96


def fcn(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2

fcn.errordef = Minuit.LEAST_SQUARES  # also fails for LIKELIHOOD

cls = np.linspace(0, 1, 1000)[1:-1]
do_print = False
fails_after = []
for cl in cls:

    m = Minuit(fcn, x=2, y=1.3, z=1)
    m.strategy = 1  # fails for all strategies 0, 1 and 2
    m.print_level = 0

    m.migrad()  # run optimiser
    assert m.fmin.is_valid

    m2 = Minuit(fcn,
                x=m.values['x'],
                y=m.values['y'],
                z=m.values['z'])

    # m2.migrad()  # "SOLUTION" 1: Using this line makes it work (but changes maybe the minimum?

    # m2.hesse()  # calling hesse (which works) before or anywhere or multiple times does not help
    try:
        for i in range(30):  # try often enough to check if it fails
            i += 1
            # m2.reset()  # SOLUTION 2: Resetting before the MINOS call (with a new minimum)
            m2.minos(cl=cl)
    except RuntimeError as error:
        if 'Function minimum is not valid.' in error.args[0]:
            fails_after.append(i)
            if do_print:
                print(f'REPEATED MINOS CALL FAILED during {i} trials.'
                      f' The error was raised with cl={cl}: {error}')
    else:
        if do_print:
            print(f'The error was NOT raised with {i} trials and cl={cl}.'
                  f' It seems we can now safely call "MINOS" again'
                  f' as much as we like.' )

import matplotlib.pyplot as plt

plt.plot(cls, fails_after)
plt.xlabel("Confidence Level")
plt.ylabel("Failed at trial number")
plt.show()


</details>
