### ISSUE TITLE
Minuit.values[0:N] and Minuit.errors[0:N] don't work as a normal list would do

### ISSUE THREAD

**Issue by casesyh** [scikit-hep/iminuit#632]
Hi, iminuit team.

Thanks for providing the excellent python Minuit interface. I came across an issue in iminuit 2.x. Suppose V = Minuit.values has N dimensions, I found that calling V[0:N-1] works but calling V[0:N] would inflict an index error. But for a normal N dimensional list p in python, calling p[0:N] is legit. Same problem happened for Minuit.errors. To get over the problem I needed to do a trick by V = Minuit.values[0:] instead of V = Minuit.values first, then V[0:N] can be legit. It'd be convenient if I wouldn't need to do the circumvention trick.

best.

**Comment by HDembinski** [comment]
Oh, thank you for finding this bug. We want to mimic the usual slicing syntax, this will be fixed.
