### ISSUE TITLE
[BUG] repeated minos calls fail (only without having called migrad before)

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/iminuit#643]
As described in the title, multiple calls of minos (without any change in anything) will raise an error here (if migrad never ran):
https://github.com/scikit-hep/iminuit/blob/b5c3ddcfec404bbd38695a7bcd24b3f6bf367ea5/src/iminuit/minuit.py#L930

What seems weird: the number until it fails is fully deterministic _and depends on the cl chosen_. I've plotted the number of minos calls vs the cl

![image](https://user-images.githubusercontent.com/17454848/113353834-8f844d80-933e-11eb-8aa8-b2d3ff628e45.png)

Here is a minimal example (taking the basic example from the docs) to reproduce the issue:

```python
from iminuit import Minuit

def fcn(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2

fcn.errordef = Minuit.LEAST_SQUARES

m = Minuit(fcn, x=2, y=1.3, z=1)
m.migrad()

assert m.fmin.is_valid

m2 = Minuit(fcn,
            x=m.values['x'],
            y=m.values['y'],
            z=m.values['z'])
for i in range(7):  # default cl fails at 7, 6 works
    m2.minos()
```

Using a reset instead of the error (or even ignoring the error and passing) solves the problem seemingly (but I may don't understand Minuit enough for this).

The full script to reproduce the plot.

I mentioned this issue also in #631 but it may got lost, so creating a new one here.

_Sidenote: I highly assume that this is indented behavior, at least it is not documented that an error will be raised. If that is intended, I would suggest to write that in the docs._

<details>
<summary>Details</summary>

from iminuit import Minuit
import numpy as np

cl = 0.688 # Fails after three for >= 0.96

def fcn(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2

fcn.errordef = Minuit.LEAST_SQUARES  # also fails for LIKELIHOOD

cls = np.linspace(0, 1, 1000)[1:-1]
do_print = False
fails_after = []
for cl in cls:

    m = Minuit(fcn, x=2, y=1.3, z=1)
    m.strategy = 1  # fails for all strategies 0, 1 and 2
    m.print_level = 0

    m.migrad()  # run optimiser
    assert m.fmin.is_valid

    m2 = Minuit(fcn,
                x=m.values['x'],
                y=m.values['y'],
                z=m.values['z'])

    # m2.migrad()  # "SOLUTION" 1: Using this line makes it work (but changes maybe the minimum?

    # m2.hesse()  # calling hesse (which works) before or anywhere or multiple times does not help
    try:
        for i in range(30):  # try often enough to check if it fails
            i += 1
            # m2.reset()  # SOLUTION 2: Resetting before the MINOS call (with a new minimum)
            m2.minos(cl=cl)
    except RuntimeError as error:
        if 'Function minimum is not valid.' in error.args[0]:
            fails_after.append(i)
            if do_print:
                print(f'REPEATED MINOS CALL FAILED during {i} trials.'
                      f' The error was raised with cl={cl}: {error}')
    else:
        if do_print:
            print(f'The error was NOT raised with {i} trials and cl={cl}.'
                  f' It seems we can now safely call "MINOS" again'
                  f' as much as we like.' )

import matplotlib.pyplot as plt

plt.plot(cls, fails_after)
plt.xlabel("Confidence Level")
plt.ylabel("Failed at trial number")
plt.show()

</details>

**Comment by HDembinski** [comment]
Thanks for the minimal example to reproduce the problem, that was very helpful. You found a really interesting bug. It turns that repeated calls to m2.minos() eventually exhaust the allowed number of functions.

The reason for that was a logic error in the code that caused superfluous calls to MnHesse with a function call count that was not reset between calls and kept increasing.

**Comment by mayou36** [comment]
Ah, that makes sense! Thanks a lot for looking at it, I would never have guessed that. Yes, it seemed like something quite exotic that I came across
