### ISSUE TITLE
Wrong start value when using fixed variables

### ISSUE THREAD

**Issue by smem2709** [scikit-hep/iminuit#648]
When using "m.fixed['a'] = False", the starting value for parameter 'b' is now the starting value for parameter 'a', i.e. -17 instead of 30. 'b' has the correct starting value if using "m.fixed['a'] = True".

I'm using version 2.6.0 but it's the same in 2.4.0. Here is a small code example:

```py
from iminuit import Minuit

t = [0,1]
data = [2,5]
def cost(a,b):
    print(a,b)

    cost = 0
    for i in range(2):
        cost += pow(data[i]-(a+b*t[i]),2.0)
    return cost

m = Minuit(cost, a=-17, b=30)
m.fixed['a'] = False
m.errordef = 1
m.migrad()
print(m.params)
```

**Comment by HDembinski** [comment]
Wow, I can confirm, this is super weird and bad. I will try to fix this ASAP.

**Comment by HDembinski** [comment]
It is a bug upstream in C++ Minuit2, see https://github.com/root-project/root/pull/8175

**Comment by HDembinski** [comment]
fixed in develop (probably will be fixed upstream in ROOT soon, too)
