### ISSUE TITLE
Allow calling scipy and nlopt minimizers from Minuit object

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#654]
We already support mixing Minuit with other minimisers, but we do not provide a convenient interface for this. Something like this should work:
```py
def fcn(a, b, c): [...]

m = Minuit(fcn, a=1, b=2, c=3)
m.scipy(method=...) # only works if scipy is installed
# optionally run m.migrad()
m.hesse()

# OR

m = Minuit(fcn, a=1, b=2, c=3)
m.nlopt(method=...) # only works if nlopt is installed
m.hesse()
```
For this to work, scipy and nlopt have to get access to the parameter limits and only see the parameters that are not fixed. The results need to be converted into Minuits internal C++ structures.

**Comment by HDembinski** [comment]
In particular this would enable global optimization without extra steps.

**Comment by matthewfeickert** [comment]
This seems nice and might be useful for `pyhf`. :+1: cc @lukasheinrich @kratsg
