### ISSUE TITLE
How can I use iminuit on python2.7?

### ISSUE THREAD

**Issue by Daren7** [scikit-hep/iminuit#666]
It seems that I can only use iminuit on python3, but I have some code that must use python2.7, so how can I use iminuit on python2.7? I use pip2 install iminuit, but there always error.

**Comment by Daren7** [comment]
I got it. iminuit==1.3.7 is still available on python 2.7.

**Comment by HDembinski** [comment]
Yes, the only solution is to use an old version. I probably do not have to tell you, but you should really try to upgrade your code to 3.x.
