### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by take2make** [scikit-hep/iminuit#671]
I tried to intall iminuit in python3:
* pip install iminuit
* pip install git+https://github.com/scikit-hep/iminuit@develop#egg=iminuit

But always I get the same error:
```bash
ModuleNotFoundError: No module named 'iminuit'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-id2hhz8v/iminuit/

```

**Comment by HDembinski** [comment]
`pip install iminuit` should definitely work if you are on a supported platform, which is linux, mac, windows, for python 3.6 to 3.9. If you are using a different platform or a different python version, let me know. Perhaps something is wrong with the sdist package.

Did you upgrade your `pip` to latest version?

**Comment by HDembinski** [comment]
Installing from the sdist package works fine. I am closing this, but feel free to reopen if you can provide more information what is not working.
