### ISSUE TITLE
Normalization of BinnedNLL?

### ISSUE THREAD

**Issue by mmakster** [scikit-hep/iminuit#675]
I assume BinnedNLL minimizes a likelihood that is the product of Poisson terms in each bin.  The factorials in the denominators have no impact on the estimators, and presumably slow the calculation down, so they are usually omitted.  Are they included here?

I ask, because I want to write a BakerCousins likelihood ratio, where the likelihood is divided by the likelihood of a saturated data set (and the ratio should asymptotically follow a chi2), so I need to make sure both normalizations are the same.

**Comment by HDembinski** [comment]
The normalization of BinnedNLL is non-standard to improve the numerical properties.
See
https://github.com/scikit-hep/iminuit/blob/develop/src/iminuit/cost.py#L556
which calls
https://github.com/scikit-hep/iminuit/blob/develop/src/iminuit/cost.py#L33
which in turn calls for ordinary binned data (no weights)
https://github.com/scikit-hep/iminuit/blob/develop/src/iminuit/cost.py#L28

The extra term `n * np.log(n + 1e-323)` term is not there in the usual calculation.

**Comment by HDembinski** [comment]
To use your own calculation, you could inherit from `BinnedNLL` and implement your own version of `_call`. Or write your own variant of `BinnedNLL`. One of the benefits of using iminuit and not some higher-level tool is that it is easy to write your own cost function.

**Comment by HDembinski** [comment]
PS: I think the normalization that I use is actually the Baker-Cousins likelihood ratio, but please check.

**Comment by mmakster** [comment]
Thank you for the information.  To check, I have written my own Baker-Cousins likelihood, and obtain the same values as BinnedNLL, confirming your normalization is Baker-Cousins in fact.  The information isn't easy to find, and I encourage you to add it someplace in the documentation (eg https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.cost.ExtendedBinnedNLL).
