### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [scikit-hep/iminuit#676]
Problem
---------
On aarch64, pip install iminuit builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install iminuit should download the wheels from pypi

@HDembinski, Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by HDembinski** [comment]
Thank you for the contribution. Building the wheels now takes forever, but I guess we can live with that.
