### ISSUE TITLE
issue with 'draw_mncontour'

### ISSUE THREAD

**Issue by girishky** [scikit-hep/iminuit#702]
Hello,
In the iminuit basic_tutorial.ipynb, when I run  the given example
`m.draw_mncontour("α", "β", cl=(0.68, 0.9, 0.99))`
it leads to following error:
`ValueError: 'codes' must be a 1D list or array with the same length of 'vertices'. Your vertices have shape (101, 2) but your codes have shape (100,)`

I think it has something to do with this line
https://github.com/scikit-hep/iminuit/blob/23be056e6d25b1c27df6f0529d5d050e5ed8fb2f/src/iminuit/minuit.py#L1862

Intriguingly, the above issue happens on M1 Mac-mini. On my Macbook (intel), I don't face any such issue.

best regards

**Comment by henryiii** [comment]
Ahh, this is what's breaking #704 and #703 - Matplotlib 3.5 changed something. If you pin to Matplotlib 3.4, it will work. Hopefully will figure out why this is broken soon.

**Comment by HDembinski** [comment]
Thank you both for looking into this and sorry for the long wait, this will be fixed now.
