### ISSUE TITLE
Migrad vs Hesse results in `Minuit.fmin`

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/iminuit#713]
Hi, I noticed that the fit results shown via `Minuit.fmin` include results from Hesse, even though the table only mentions Migrad at the top. Is this behavior intended?

Here is an example, I am using `iminuit` 2.9.0:
```python
from iminuit import Minuit

def fcn(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2

fcn.errordef = Minuit.LEAST_SQUARES

m = Minuit(fcn, x=0, y=0, z=0)
m.print_level = 1
res = m.migrad(ncall=25)
print("after MIGRAD:")
print(m.fmin)

m.hesse()
print("\nafter HESSE:")
print(m.fmin)
```

Output:
```
W MnHesse Maximum number of allowed function calls exhausted; will return diagonal matrix
W VariableMetricBuilder Invalid Hessian - exit the minimization
after MIGRAD:
┌─────────────────────────────────────────────────────────────────────────┐
│                                Migrad                                   │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 6.731e-18                  │              Nfcn = 27               │
│ EDM = 6.73e-18 (Goal: 0.0002)    │                                      │
├──────────────────────────────────┼──────────────────────────────────────┤
│         INVALID Minimum          │        No Parameters at limit        │
├──────────────────────────────────┼──────────────────────────────────────┤
│ Below EDM threshold (goal x 10)  │           ABOVE call limit           │
├───────────────┬──────────────────┼───────────┬─────────────┬────────────┤
│  Covariance   │     Hesse ok     │APPROXIMATE│NOT pos. def.│ Not forced │
└───────────────┴──────────────────┴───────────┴─────────────┴────────────┘

after HESSE:
┌─────────────────────────────────────────────────────────────────────────┐
│                                Migrad                                   │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 6.731e-18                  │              Nfcn = 43               │
│ EDM = 6.73e-18 (Goal: 0.0002)    │                                      │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Valid Minimum           │        No Parameters at limit        │
├──────────────────────────────────┼──────────────────────────────────────┤
│ Below EDM threshold (goal x 10)  │           Below call limit           │
├───────────────┬──────────────────┼───────────┬─────────────┬────────────┤
│  Covariance   │     Hesse ok     │ Accurate  │  Pos. def.  │ Not forced │
└───────────────┴──────────────────┴───────────┴─────────────┴────────────┘
```

I used to run both Migrad and Hesse, and only check results after both of these steps, thinking issues would still be reflected in the final `Minuit.fmin` object. This is not the case, and the original failure (due to the artificial `ncall` limitation) is no longer reflected at the end.

I see the benefit in also being able to get information about how the Hesse calculation went. It was not clear to me so far that these appear in the table, given its title and the presence of other results from Migrad (FCN / EDM, which I guess have no equivalent in Hesse and therefore stay unchanged). Maybe the title of the table could reflect that it is not only Migrad information which is being shown here?

**Comment by HDembinski** [comment]
Yes, MINUIT with strategy 1 (default) runs MnHesse automatically after Migrad (not always, but most of the time). This is how it is implemented in C++.

If you do not want that, you can set Minuit.strategy = 0.

**Comment by HDembinski** [comment]
Regarding the apparently inconsistent behavior, it is not inconsistent. The first call ended abnormally because MnHesse ran into the call limit. The EDM is tiny, which suggests the fit was ok, but EDM is computed taking the covariance matrix into account, which cannot be trusted, since MnHesse returned a dummy matrix, which happens to be correct in your case by accident. So the minimum is invalid (as we cannot be sure that it is valid).

Then you run MnHesse, which recomputes the covariance matrix, now without a call limit. Edm is calculated again now with the correct matrix and it turns out that Edm is below the tolerance, so MINUIT reports that now not only the matrix is ok but also the minimum is valid.

**Comment by alexander-held** [comment]
Thank you very much for the explanation! I understand now how the minimum becomes valid after the Hesse call.

The report about hitting the function call limit may be slightly misleading in the final output: In the Hesse call, this limit was not reached, so I understand why the final result reports that. The call limit was reached in the Migrad step though, so a user who does not check before Hesse (or look at terminal output) will miss that. Since the table is titled "Migrad" still, that suggests that Migrad encountered no issues. A setup where this may matter is if the minimum is still invalid after Hesse due to insufficient Migrad calls. The user may miss that information of how to resolve the fit failure when only looking at the summary report at the end. I believe this pattern of explicitly calling Hesse right after Migrad might be a common one, as it is suggested in [section 7.2.2 of the reference manual](https://root.cern.ch/download/minuit.pdf). This is probably not a big issue though, as the information is conveyed by other terminal output regardless.
