### ISSUE TITLE
Add `to_dict` method to Matrix

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#721]
`BasicView` has a `to_dict` method. For symmetry, `Matrix` should also have such a method.

**Comment by jamesdeeel** [comment]
Hi, I happened to be thinking about this also this morning. What do you think would be the preferable way of making it into a dict?

Say we had some element in the matrix corresponding to the correlation between params a and b as `M_{ab}`
The two natural options to me are having single dict with the keys as pairs of names `{("a", "a"):M_{aa}, ("a", "b") :M_{ab}, ... }` or as a `dict` of `dict`s with each one corresponding to a row of the `Matrix` so `{"a":{"a":M_{aa}, "b":M_{ab},...},...}`

What are your thoughts?

**Comment by HDembinski** [comment]
As you can see, I chose the former. You make a good point, but I think the choice was right.
`d["a", "b"]` is less typing than `d["a"]["b"]`, and the data structure with a single dict is more efficient and simpler than one with nested dicts.
