### ISSUE TITLE
Allow users to chose their own grid for mncontour, mnprofile

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#745]
@iasonkrom wrote on Gitter:

> May I suggest a small iminuit feature that I would find useful?
I think in methods like mnprofile and mncontour It would be really nice to have the ability to scan on points that are evenly spaced on a log scale.
> I had to do this recently using iminuit because one fitting parameter was the thermal cross section for a generic WIMP. Of course I wrote a for loop myself to do this but it would be nice to have it built in since you already have the linear scanning.
> Or maybe just allow the user to choose the points as input so they can use np.logspace for that.
if that already exists and I'm completely blind and don't see it in the documentation then I'm sorry.

**Comment by HDembinski** [comment]
@iasonkrom I think this is an easy issue to contribute yourself if you like. I would be happy to review a PR.

**Comment by iasonkrom** [comment]
I'm just a measly student who is starting his PhD in September and has never contributed to open-source in his life.
I really don't think you want me to do that haha :). I was just making a suggestion that I would find interesting.

**Comment by HDembinski** [comment]
It is easier than you think, we have a contributing guide, see CONTRIBUTING.md. The "hardest part" is to set up the development environment, but that's described in CONTRIBUTING.md. Submitting PRs and getting guided by code review is a good way to learn about best practices in coding, although it requires some patience and willingness to learn.

**Comment by HDembinski** [comment]
If you don't want to contribute, you can also help by starring iminuit if you like it. Thank you!

**Comment by iasonkrom** [comment]
> If you don't want to contribute, you can also help by starring iminuit if you like it. Thank you!

That's been done a long time ago. Been using it extensively for a year now for almost all my optimization/minimization problems. Great project!
