### ISSUE TITLE
`Minuit.ncall` and `Minuit.get_num_call_fcn()` suggestions for improvements

### ISSUE THREAD

**Issue by cdeil** [scikit-hep/iminuit#75]
Examples are here: http://nbviewer.ipython.org/4655035/

The issues are:
- `Minuit.ncalls` is updated to the number of function calls for MIGRAD and HESSE, it should also be updated for MINOS
- `Minuit.print_fmin()` displays `Minuit.ncalls` as `NFCN` and  `Minuit.get_num_call_fcn()` as `NCALLS`. This is confusing that `Minuit.ncalls` doesn't correspond to `NCALLS`
- `Minuit.ncalls` doesn't have a docstring
- `Minuit.ncalls` is a float. Why not an int?
- Maybe `Minuit.get_num_call_fcn()` could be exposed as a property like `Minuit.ncalls_total`?

**Comment by HDembinski** [comment]
Can we close this? Sounds like it was fixed.
