### ISSUE TITLE
Cannot pickle MaskedCost objects starting with version 2.12

### ISSUE THREAD

**Issue by jlabounty** [scikit-hep/iminuit#770]
Hello, 

I recently updated my version of iminuit:
```
2.11.2-py310hd8f1fbe_1 --> 2.12.2-py310hd8f1fbe_0
```
and found that I was no longer able to pickle classes which inherit from MaskedCost. I think the issue is due to the [definition](https://github.com/scikit-hep/iminuit/blob/develop/src/iminuit/cost.py#L625) of `up()` within the `__init__` function. 

Here is a minimal code snippet to illustrate the problem. It executes without error on version `2.11.2` and does not work on `2.12.2` (and `2.14`):
```
import iminuit
import pickle 
from iminuit.cost import LeastSquares
print(f"{iminuit.__version__=}")

def func(x,p):
    return x*p[0] + p[1]

c = LeastSquares([1,2,3,4], [1,2,3,4], [1,1,1,1], func)
print(c)

with open('./test.pickle', 'wb') as fout:
    pickle.dump(c,fout)

with open("./test.pickle", 'rb') as fin:
    loaded = pickle.load(fin)
print(loaded)
```

```
>>>python --version
Python 3.10.5
>>> python bug.py 
iminuit.__version__='2.12.2'
<iminuit.cost.LeastSquares object at 0x7fbf16438040>
Traceback (most recent call last):
  File "/home/jlab/github/g2_analysis/analysis/bug.py", line 13, in <module>
    pickle.dump(c,fout)
AttributeError: Can't pickle local object 'MaskedCost.__init__.<locals>.up'
```
vs.
```
>>>python bug.py 
iminuit.__version__='2.11.2'
<iminuit.cost.LeastSquares object at 0x7fce63d1bed0>
<iminuit.cost.LeastSquares object at 0x7fce62a52960>
```

Thank you!

**Comment by HDembinski** [comment]
Thank you very much for reporting this. It sad to see that this was not caught by the existing unit tests. I will try to fix this in the next version.

**Comment by jlabounty** [comment]
Thank you very much for the quick response!
