### ISSUE TITLE
docs: function name for SciPy-like interface

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/iminuit#775]
Hi, while trying out the SciPy-like interface to `iminuit` I noticed that the docs list the relevant function as `iminuit.minimize.minimize` (https://iminuit.readthedocs.io/en/latest/reference.html#iminuit.minimize.minimize). As far as I can tell, the function should be `iminuit.minimize` instead:
```python
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:25:34)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import iminuit
>>> iminuit.__version__
'2.15.1'
>>> iminuit.minimize
<function minimize at 0x10630d550>
>>> iminuit.minimize.minimize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'minimize'
```
The function is available at the top level via
https://github.com/scikit-hep/iminuit/blob/2012c5da71ce26b011c85beefde3423b3979a88a/src/iminuit/__init__.py#L30
and I am guessing that Sphinx autodoc may not understand that, as it currently documents the module `iminuit.minimize` and then finds the `minimize` function inside that:

```
.. automodule:: iminuit.minimize
    :members:
```

**Comment by HDembinski** [comment]
Thanks, this is a left-over from refactoring, will be fixed! Do you want to submit a quick PR with this change? I would highly appreciate it.

**Comment by HDembinski** [comment]
However, you are right that it is inconsistent with `iminuit.minuit.Minuit`, where the docs also just list `iminuit.Minuit`.
