### ISSUE TITLE
Add Minuit.visualize

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/iminuit#790]
Some cost functions can be visualized. To visualize the fitted model, one does

```py
m = Minuit(mycost, ...)
m.migrad()
mycost.visualize(m.values)
```

To simplify this, add a `visualize` method to `Minuit`, so that the following works

```py
m.visualize()  # calls mycost.visualize(m.values) if mycost.visualize exists or raises an exception
```

**Comment by jsaarela1** [comment]
Hi, I would like to give this issue a try.

**Comment by HDembinski** [comment]
@jsaarela1 Sure, go ahead! Please have a look at CONTRIBUTING.md, which explains how to set up iminuit for development.
