### ISSUE TITLE
iminuit

### ISSUE THREAD

**Issue by LL-RL** [scikit-hep/iminuit#801]
(1) I used to call m.interactive() in jupyter lab, but it shows that 'Minuit' object has no attribute 'interactive'.
(2) When I use the following code to fit a self-defined function, the returned result is always equal to the initial value given initially, and no value is given for the fit.

import numpy as np
from scipy.optimize import curve_fit
from scipy.stats import norm
from iminuit import Minuit, cost
from iminuit.cost import UnbinnedNLL, BinnedNLL

truth = 10, 10, 0.6, 10, 20, 0.8
def pdf_mulit_lognormx(x, 
                       A0, pos0, wid0, 
                       A1, pos1, wid1, 
                       #A2, pos2, wid2
                      ):
    return (
             #A0 * np.exp( -((np.log(x) - np.log(pos0)) / wid0)**2) 
            #+ A1 * np.exp( -((np.log(x) - np.log(pos1)) / wid1)**2)
            #+ A2 * np.exp( -((np.log(x) - np.log(pos2)) / wid2)**2)
        A0*norm.cdf(x, pos0, wid0) + A1*norm.cdf(x, pos1, wid1)
           )

#nt, bins, patches = plt.hist(source_data['flux'], 10)

#bin_centers = (bins[:-1]+bins[1:])//2
#popt, pcov = curve_fit(pdf_mulit_lognormx, bin_centers, nt)
#print(hist, bin_centers)   
#print(popt)

x = np.linspace(0,1)

m = np.diff(pdf_mulit_lognormx(x, *truth))

n = np.random.default_rng(1).poisson(m)

c = cost.ExtendedBinnedNLL(n, x, pdf_mulit_lognormx)
m = Minuit(c, *truth)
m.interactive()
m.migrad()  # run optimiser
m.hesse()   # run covariance estimator

print(m.values)  # x: 2, y: 3, z: 4
print(m.errors)  # x: 1, y: 1, z: 1

return <ValueView A0=10.0 pos0=10.0 wid0=0.6 A1=10.0 pos1=20.0 wid1=0.8>
          <ErrorView A0=0.0 pos0=0.0 wid0=0.0 A1=0.0 pos1=0.0 wid1=0.0>

**Comment by HDembinski** [comment]
We discussed this in the Discussion section.
