### ISSUE TITLE
TypeError: migrad() got an unexpected keyword argument 'precision'`

### ISSUE THREAD

**Issue by JaySandesara** [scikit-hep/iminuit#807]
Hello,

I am facing the same issue mentioned in the comments [here](https://github.com/scikit-hep/iminuit/issues/142) with using the precision argument in migrad. I recreated the exact example @cdeil mentioned:

```
from iminuit import Minuit 

def f(x, y, z): 
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2 

m = Minuit(f) 
m.migrad(precision=0.1)
```

And I end up getting the error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-32-69b3633f7d19> in <module>
      4 
      5 m = Minuit(f, (0.0,0.0,0.0))
----> 6 m.migrad(precision=0.1)

TypeError: migrad() got an unexpected keyword argument 'precision'
```

Can you please help? I am using iminuit v2.16.0.

**Comment by JaySandesara** [comment]
I am also getting the following error while trying to save an instance using fitarg:

AttributeError: 'Minuit' object has no attribute 'fitarg'

**Comment by JaySandesara** [comment]
The errors seem to be resolved when I switched back to v1.5.4. Is this the only solution?

**Comment by JaySandesara** [comment]
Apologies, but I just realized that I was reading the wrong version of readthedocs:  https://iminuit.readthedocs.io/en/latest/reference.html#iminuit.Minuit.precision as reference. Switched to the latest one and I realize that I needed to set the precision directly on the Minuit instance.

**Comment by HDembinski** [comment]
Glad to hear that the docs were able to resolve this. Thanks for reaching out.
