### ISSUE TITLE
Provide macOS Monterey and Ventura wheels

### ISSUE THREAD

**Issue by nega0** [scikit-hep/iminuit#814]
As I'm sure you're aware the Github actions runner image `macos-latest` still points to Big Sur. `macos-12` is the runner image for Monterey. Up-to-date wheels would be super helpful for `pip`ing in `iminuit` and prevent issues like #813. 

Unfortunately, as was unofficially announced just yesterday (https://github.com/actions/runner-images/issues/6426#issuecomment-1341047365), the Ventura image won't be available until Q2. I can provide a Ventura self-hosted runner in the meantime.

**Comment by HDembinski** [comment]
@henryiii As the packaging expert, do you have thoughts on this?

You seem to understand much more about this than I do. We can switch from macos-latest to macos-12 when building the wheels if that helps.

**Comment by henryiii** [comment]
You do _not_ need to build on the latest macOS. On macOS, you set MACOSX_DEPLOYMENT_TARGET to the oldest macOS you support, and the stdlib will only include binary components that support that version - or any newer version. So it's generally safe to upgrade to a newer macOS, but you do not _need_ to. The only benefit is you might get access to newer header only changes (but this is C++11 IIRC, so unlikely to benefit). That's not the problem in that issue at all.

Wheels list some version they target, then they work on all newer versions, following the way macOS works. Run `pip debug --verbose` and you'll see everything your current version supports - you'll see all older macOS versions listed there.

**Comment by henryiii** [comment]
Looks like 3.11 was missed here:

https://github.com/scikit-hep/iminuit/blob/e6365013ef1362b06b5acc8cd28106b61cf4bfca/.github/workflows/release.yml#L40-L48

**Comment by HDembinski** [comment]
Release 2.18.0 contains a Python3.11 wheel for macos universal2

**Comment by HDembinski** [comment]
If there are still issues, ping me and reopen.

**Comment by nega0** [comment]
Confirmed availability w/ python 3.11 on Ventura. Thanks!
