### ISSUE TITLE
Problem with installation using pip3

### ISSUE THREAD

**Issue by hashamipour** [scikit-hep/iminuit#824]
I'm trying to install iminuit on a cluster. I get the following error:
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n9y3oi03/iminuit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3wkoghnp-record/install-record.txt --single-version-externally-managed --prefix /data/hashami/local --compile" failed with error code 1 in /tmp/pip-build-n9y3oi03/iminuit/
OS Description:	CentOS Linux release 7.9.2009
Python : 3.6.8
iminuit : 2.16 or not specified
command: pip3 install iminuit==2.16 --prefix=/data/hashami/local
What is the cause? Can you help?
I don't have the conda option available. Running python3 on setup.py gives a similar error.

**Comment by HDembinski** [comment]
Your Python version is too old to get most recent iminuit version. Try `pip3 install --prefer-binary iminuit`, that should give you the last version for which we generated wheels.

**Comment by hashamipour** [comment]
Thanks, Hans :100:
