### ISSUE TITLE
Specify required version of numpy

### ISSUE THREAD

**Issue by maxnoe** [scikit-hep/iminuit#845]
iminuit is currently missing a version requirement on numpy but requires a relatively recent version.

This leads to import errors when pinning the numpy version to an older version, since pip and conda cannot know that newer versions of iminuit are not compatible.

The specific error I encountered is:

```
ImportError: cannot import name 'NDArray' from 'numpy.typing' (/home/mnoethe/.local/conda/envs/icrc2021-pipelines/lib/python3.8/site-packages/numpy/typing/__init__.py)
```

which was introduced in versions 1.21, so at this moment, this would be the minimum required numpy version iminuit needs to require.

**Comment by HDembinski** [comment]
Thanks for reporting this, will be fixed.
