### ISSUE TITLE
[bug]: annotation evaluation breaks non-standard delayed annotation evalutation

### ISSUE THREAD

**Issue by jonas-eschle** [scikit-hep/iminuit#846]
The added evaluation of delayed annotations (https://github.com/scikit-hep/iminuit/blob/develop/src/iminuit/util.py#L1313) only works with annotation from the Typing module and will fail with custom annotations (as they're not in the `Typing` namespace).

Example (this is a simplified example to illustrate the case! In this, *oversimplified*, example, we could simply remove the delayed annotation and bind the actual pandas DF. That's not the point, it's just to illustrate the problem with delayed annotations and different namespaces that we experience):
```
import pandas as pd  # this could be any library
from iminuit import cost

def f(x, mu: "pd.DataFrame"):
    return x * mu
    
nllfail = cost.UnbinnedNLL([3, 4], f)  # this fails with a name error as "pd" is not defined in the eval scope
```

**Comment by HDembinski** [comment]
Thanks for reporting this, the evaluation needs to be made more flexible. I will try to fix this, but it also makes no sense to have "pd.DataFrame" as the annotation for the parameter of a model, because that is expected to be a floating point type.

**Comment by HDembinski** [comment]
There are lots of issues with string annotations, see https://peps.python.org/pep-0649/ and the discussion in https://github.com/scikit-hep/iminuit/pull/839.
