### ISSUE TITLE
Suppression of Migrad output

### ISSUE THREAD

**Issue by MACampana** [scikit-hep/iminuit#898]
Hi, I am using `iMinuit` version 2.18.0. I am wondering if there is a way, or an implementation could be made, to suppress (all) output from `migrad` and similar fitting functions. For example, running `Minuit.migrad()` will produce an output along the lines of:

```
┌─────────────────────────────────────────────────────────────────────────┐
│                                Migrad                                   │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = -0.06308                   │              Nfcn = 325              │
│ EDM = 7.41e-09 (Goal: 0.0002)    │                                      │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Valid Minimum           │       SOME Parameters at limit       │
├──────────────────────────────────┼──────────────────────────────────────┤
│ Below EDM threshold (goal x 10)  │           Below call limit           │
├───────────────┬──────────────────┼───────────┬─────────────┬────────────┤
│  Covariance   │     Hesse ok     │ Accurate  │  Pos. def.  │ Not forced │
└───────────────┴──────────────────┴───────────┴─────────────┴────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ ns   │    1e3    │    4e3    │            │            │    0    │1.12076e+09│       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘
┌────┬──────────┐
│    │       ns │
├────┼──────────┤
│ ns │ 1.86e+07 │
└────┴──────────┘
```
I would like to suppress this output when performing a high number of minimizations as to avoid unnecessarily long outputs especially during interactive (i.e., command line or Jupyter Notebook) usage. Other ways of suppressing output such as [here ](https://stackoverflow.com/questions/2125702/how-to-suppress-console-output-in-python) or [here](https://stackoverflow.com/questions/2828953/silence-the-stdout-of-a-function-in-python-without-trashing-sys-stdout-and-resto) seem to not work (I guess the way that `iMinuit` displays the above output is not aligned with these suppression methods).

**Comment by HDembinski** [comment]
iminuit generates no output to the console. What you are showing here is the representation of the Minuit object after fitting, which IPython renders in this way. To suppress that you simply put a semicolon `;` after the command. When you don't run interactively, you won't see it either.
