### ISSUE TITLE
Error in iminuit.util.describe

### ISSUE THREAD

**Issue by rferguson22** [scikit-hep/iminuit#905]
When trying to run the code on generic least squares function page (https://iminuit.readthedocs.io/en/stable/notebooks/generic_least_squares.html), there is an error trying to run the describe function. It is because there are two functions both called iminuit.util.describe (https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.util.describe) and the generic least squares requires the version with 2 callable parameters which is being supressed by the version with 1 callable parameters.

**Comment by HDembinski** [comment]
Hi @rferguson22 thanks for the report. I cannot reproduce this on my machine with the latest version.

**Comment by HDembinski** [comment]
Please reopen if the problem is not solved.
