### ISSUE TITLE
Update multiprocessing tutorial example

### ISSUE THREAD

**Issue by cdeil** [scikit-hep/iminuit#93]
@piti118 In the tutorial [here](http://nbviewer.ipython.org/urls/raw.github.com/iminuit/iminuit/master/tutorial/hard-core-tutorial.ipynb)
you say this:

> You might be worried about that forking process will copy your data. Most modern OS use Copy On Write(look at wiki) what this means is that when it forks a process it doesn't copy memory there unless you are writing it

and in the code:

> # Copy on write ensures that data points will never be copied (unless your write to it)

Are you sure this is true?
I haven't tested myself, but from what I read this `copy on write` trick doesn't work in Python: see e.g. http://stackoverflow.com/a/660026/498873 .

Also the multiprocessing example references an IPython issue that has been closed.

@piti118 Can you update this example?

**Comment by HDembinski** [comment]
We have a numba tutorial with parallel processing now.
