### ISSUE TITLE
Better documentation for errordef

### ISSUE THREAD

**Issue by iguinn** [scikit-hep/iminuit#930]
Please document which cost functions require which values for errordef. For example, the ExtendedUnbinned cost function actually uses errordef=1, which was surprising to me since I was expecting it to act like a likelihood rather than a chi-square function (I actually think it's great, especially for beginners, that by default one does not need to set errordef for this). I would suggest adding a quick sentence to each cost function in the documentation telling people what to use for errordef (I looked at the actual implementation of the function to figure this out!)

**Comment by HDembinski** [comment]
For all the builtin cost functions you don't need to set errordef. I will try to warn users when they manually setting errordef for those cost functions which already define the errordef.
