### ISSUE TITLE
CostSum support for cost functions accepting a parameter array

### ISSUE THREAD

**Issue by lvarriano** [scikit-hep/iminuit#941]
Hello - I would like to add a `NormalConstraint` to an `ExtendedBinnedNLL` for one or more parameters. As noted in the [docs](https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.cost.CostSum), `CostSum` does not currently support cost functions that accept a parameter array. However, my model has tens of background components, each with a different strength parameter. I would like the ability to quickly adjust the number of components in the fit, which would be limited if I need to explicitly define each parameter in the model function. 

Using a model function that takes an array of parameters, if I set the `ExtendedBinnedNLL._parameters` to a dictionary of the parameters, then I can add a `NormalConstraint` to it, and the fit seems to work perfectly. I attached a MWE. [mwe.txt](https://github.com/scikit-hep/iminuit/files/12678090/mwe.txt)

Instead of accessing the internal `_parameters` myself, would it be possible to add a method to the `Cost` class that looks like the following? This seems to work for my problem, but I have not done extensive testing.

```
    @property
    def parameters(self):
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: Dict[str, Optional[Tuple[float, float]]]):
        self._parameters = parameters
```
Alternatively, if it were possible to pass a `name` option to the `ExtendedBinnedNLL` class (and similar classes) as in the `Template` class, this should also fix the issue and is probably more consistent with the existing structure. It is already possible to add a `Template` to a `NormalConstraint` with no problem thanks to this.

**Comment by lvarriano** [comment]
Thanks for the detailed explanation and for pointing me towards `iminuit.utils.describe`!

**Comment by HDembinski** [comment]
It took me a while, but a PR is in progress @lvarriano

**Comment by lvarriano** [comment]
That's great, thanks so much!
