### ISSUE TITLE
Misleading documentation for iminuit.util.make_with_signature()

### ISSUE THREAD

**Issue by johashei** [scikit-hep/iminuit#949]
The object returned by `make_with_signature()` cannot be called with keyword arguments. However the current documentation simply states:
> Return new callable with altered signature.
[...]
**Return type:**  callable with new argument names.

This leads to the expectation that the new callable behaves as if it had been defined with the new arguments. It’ll be helpful if the inability to take keyword arguments is mentioned explicitly.

**Comment by HDembinski** [comment]
Thanks for the report. I will correct the documentation.
