### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by cdeil** [scikit-hep/iminuit#960]
Hi - could you please support and create binary package for Python 3.12?

I didn't see anything with "312" here:

https://anaconda.org/conda-forge/iminuit/files
https://pypi.org/project/iminuit/2.24.0/#files

Concretely I tried to use Python 3.12 with Conda-forge and got this error:
```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides _python_rc needed by python-3.12.0rc3-rc3_h47c9636_1_cpython

Could not solve for environment specs
The following packages are incompatible
├─ iminuit is installable with the potential options
│  ├─ iminuit [2.0.0|2.10.0|...|2.8.4] would require
│  │  └─ python_abi 3.8.* *_cp38, which can be installed;
│  ├─ iminuit [2.0.0|2.10.0|...|2.8.4] would require
│  │  └─ python_abi 3.9.* *_cp39, which can be installed;
│  ├─ iminuit [2.10.0|2.11.2|...|2.8.4] would require
│  │  └─ python_abi 3.10.* *_cp310, which can be installed;
│  └─ iminuit [2.17.0|2.18.0|...|2.24.0] would require
│     └─ python_abi 3.11.* *_cp311, which can be installed;
└─ python 3.12**  is not installable because there are no viable options
   ├─ python [3.12.0|3.12.1] would require
   │  └─ python_abi 3.12.* *_cp312, which conflicts with any installable versions previously reported;
   └─ python 3.12.0rc3 would require
      └─ _python_rc, which does not exist (perhaps a missing channel).
```

I'll use 3.11 for now.

**Comment by hepkosmos** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-01-19T20:24:53
          
          
            * 메일 제목 : 
[scikit-hep/iminuit] Python 3.12 support (Issue #960)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by HDembinski** [comment]
Yes, will be supported in the next release.

**Comment by HDembinski** [comment]
The release 2.25 is out now, with CPython-3.12 wheels.

**Comment by cdeil** [comment]
Wonderfull! Thank you!


And also I see iminuit conda packages for Python 3.12 are also already out here:
https://anaconda.org/conda-forge/iminuit/files

And for me on MacOS this works perfectly:
```
conda create -n iminuit-env-312 python=3.12 iminuit
```

Now waiting for DuckDB release to support 3.12 I think very soon and then we can update. :-)

**Comment by HDembinski** [comment]
Just out of curiosity, why the rush toward the latest Python release?

**Comment by cdeil** [comment]
No big reason. We are currently on Python 3.10 which is from 2021. We could just stay another year on it. But I think it's also nice for devs to learn and use the new and better version, and should we do the version upgrade this year I'd prefer to directly jump to 3.12. :-)

It's great that you added the support - now everyone can choose what they like.

**Comment by HDembinski** [comment]
Apart from ever better typing support, a major reason for wanting to move to 3.11 is the speed-up. But 3.12 did not bring dramatic new features, that's why I was asking.
