### ISSUE TITLE
Crash in visualization

### ISSUE THREAD

**Issue by claudiocc1** [scikit-hep/iminuit#966]
hi,

I went back to an old project.  It used to work with the then-current version of iminuit. Sorry, cannnot remember the exact version.  Now it crashes with iminuit 2.25 (python 3.11.5, Intel Mac.).

The fit actually works, and gives the exact same result now as it used to.  I think the crash is in the visualization part, which I guess has been added since?  

Here you can find my jupyter notebook, stripped down to the bare minimum (html and ipynb versions)
http://hep.ucsb.edu/people/claudio/minuit/

Thanks.

Claudio

PS is there a way to turn off the visualization?

**Comment by HDembinski** [comment]
Thanks for reporting, that is indeed a bug. I will see how this can be fixed. A temporary workaround for you is
```py
# Minuit fit
p0 = np.array([2., 2., 0., -1., -1.5])
mFit = LeastSquares(x, y, ey, fitFun)
mFit.visualize = lambda x, *args: None
m = Minuit(mFit, p0)  # pass starting values
m.migrad()
# m.hesse()
```

**Comment by HDembinski** [comment]
If you want to fit a smooth function through your data points under the condition that the function $f(x) \ge 0$, you can also use Bernstein polynomials. They are guaranteed to be positive inside the domain, if all the parameters are positive. You cannot extrapolate Bernstein polynomials, though.

```py
from numba_stats import bernstein

def model(x, p):
    return bernstein.density(x, p, -0.4, 0.4)

# Minuit fit
p0 = np.ones(4)
m = Minuit(LeastSquares(x, y, ey, model), p0)  # pass starting values
m.migrad()
```

**Comment by claudiocc1** [comment]
Yes I know :)
We are working with people that like splines (I dont), so here we are....
C.

**Comment by HDembinski** [comment]
I like splines, too :). Bernstein polynomials are a special case of splines.
