### ISSUE TITLE
Error: IMinuitWarning: MIGRAD fails to converge

### ISSUE THREAD

**Issue by fgiacchi86** [scikit-hep/iminuit#994]
Hello guys,

I am using Minuit for a likelihood analysis. It seems that after a value of a parameter "x" the function could degenerate and we expect a sharp decrease in vertical way for the parameter "x=limit_value", but this not happens and the values of "y" remain constant at the value "y(limit_value)=y_limit". Why this happens? The error that I have is "IMinuitWarning: MIGRAD fails to converge for y=###"

You need all script to better understand?
Thanks

**Comment by HDembinski** [comment]
I am closing this, as this is likely not an issue in iminuit, but a problem with the model. Have a look at the new tutorial with guidance. https://scikit-hep.org/iminuit/notebooks/unstable_fit.html
